# Generated by Django 5.0.10 on 2025-10-27 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('factory', '0010_remove_factory_is_trial'),
        ('stock', '0010_alter_materialhistory_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정일')),
                ('from_unit', models.CharField(blank=True, default='', help_text='변환 전 단위', max_length=50, null=True)),
                ('to_unit', models.CharField(blank=True, default='', help_text='변환 후 단위', max_length=50, null=True)),
                ('conversion_rate', models.DecimalField(decimal_places=4, default=1, help_text='변환 비율', max_digits=10)),
                ('factory', models.ForeignKey(help_text='공장', on_delete=django.db.models.deletion.CASCADE, related_name='unit_conversions', to='factory.factory')),
                ('material', models.ForeignKey(blank=True, help_text='자재', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unit_conversions', to='stock.material')),
                ('product', models.ForeignKey(blank=True, help_text='제품', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unit_conversions', to='stock.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
