# Generated by Django 5.0.10 on 2025-10-29 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit_conversion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unitconversion',
            name='conversion_rate',
        ),
        migrations.AddField(
            model_name='unitconversion',
            name='decimal_rule',
            field=models.CharField(choices=[('round', '반올림'), ('floor', '버림'), ('ceil', '올림')], default='round', help_text='소수점 처리 방식', max_length=10),
        ),
        migrations.AddField(
            model_name='unitconversion',
            name='from_quantity',
            field=models.DecimalField(decimal_places=4, default=1, help_text='변환 전 단위의 수량', max_digits=10),
        ),
        migrations.AddField(
            model_name='unitconversion',
            name='to_quantity',
            field=models.DecimalField(decimal_places=4, default=1, help_text='변환 후 단위의 수량', max_digits=10),
        ),
    ]
