# Generated by Django 5.0.10 on 2025-07-08 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('factory', '0003_factory_billing_key_alter_factoryequipment_location_and_more'),
        ('stock', '0002_material_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정일')),
                ('transaction_date', models.DateField(help_text='거래 일자')),
                ('approval_number', models.CharField(help_text='승인번호', max_length=100)),
                ('transaction_classification', models.CharField(help_text='거래 구분', max_length=100)),
                ('transaction_purpose', models.CharField(help_text='거래 용도', max_length=100)),
                ('transaction_amount', models.IntegerField(help_text='공급 가액')),
                ('tax_amount', models.IntegerField(help_text='세액')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factory.factoryclient')),
                ('product', models.ManyToManyField(help_text='품목명', to='stock.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NationalTaxService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정일')),
                ('publish_status', models.CharField(choices=[('임시 저장', 'temporary'), ('발행 대기', 'pending'), ('발행 완료', 'published')], default='임시 저장', help_text='발행 상태', max_length=10)),
                ('tax_invoice_type', models.CharField(choices=[('매출', 'sales'), ('매입', 'purchase')], default='매출', help_text='세금계산서 유형', max_length=10)),
                ('transaction_type', models.CharField(choices=[('영수', 'receipt'), ('청구', 'invoice')], default='영수', help_text='거래 유형', max_length=10)),
                ('transaction_date', models.DateField(help_text='거래 일자')),
                ('transaction_amount', models.IntegerField(help_text='공급 가액')),
                ('tax_amount', models.IntegerField(help_text='세액')),
                ('is_hidden', models.BooleanField(default=False, help_text='숨김 여부')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factory.factoryclient')),
                ('product', models.ManyToManyField(help_text='품목명', to='stock.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
