# Generated by Django 5.0.10 on 2025-07-09 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0004_alter_factory_owner_alter_factoryclient_factory_and_more'),
        ('stock', '0004_alter_material_options_and_more'),
        ('tax', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashreceipt',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_receipts', to='factory.factoryclient'),
        ),
        migrations.AlterField(
            model_name='cashreceipt',
            name='product',
            field=models.ManyToManyField(help_text='품목명', related_name='cash_receipts', to='stock.product'),
        ),
        migrations.AlterField(
            model_name='nationaltaxservice',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_invoices', to='factory.factoryclient'),
        ),
        migrations.AlterField(
            model_name='nationaltaxservice',
            name='product',
            field=models.ManyToManyField(help_text='품목명', related_name='tax_invoices', to='stock.product'),
        ),
    ]
