# Generated by Django 5.0.10 on 2025-07-24 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0005_factorymember_invited_at'),
        ('tax', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='nationaltaxservice',
            name='factory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='national_tax_services', to='factory.factory'),
        ),
        migrations.AddField(
            model_name='nationaltaxservice',
            name='line_items',
            field=models.JSONField(blank=True, default=list, help_text='세금계산서 품목 리스트'),
        ),
        migrations.AddField(
            model_name='nationaltaxservice',
            name='user',
            field=models.ForeignKey(blank=True, help_text='사용자', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='national_tax_services', to=settings.AUTH_USER_MODEL),
        ),
    ]
