# Generated by Django 5.0.10 on 2025-07-29 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0002_nationaltaxservice_factory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nationaltaxservice',
            name='barobill_state',
            field=models.CharField(blank=True, help_text='바로빌 상태', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='nationaltaxservice',
            name='mgt_key',
            field=models.CharField(blank=True, help_text='관리 키', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='nationaltaxservice',
            name='nts_send_key',
            field=models.CharField(blank=True, help_text='국세청 승인번호', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='nationaltaxservice',
            name='nts_send_state',
            field=models.CharField(blank=True, help_text='국세청 전송 상태', max_length=30, null=True),
        ),
    ]
