# Generated by Django 5.0.10 on 2025-07-31 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0005_factorymember_invited_at'),
        ('tax', '0003_nationaltaxservice_barobill_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nationaltaxservice',
            name='client',
            field=models.ForeignKey(blank=True, help_text='거래처', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_invoices', to='factory.factoryclient'),
        ),
    ]
