# Generated by Django 5.0.10 on 2025-07-31 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0005_factorymember_invited_at'),
        ('tax', '0004_alter_nationaltaxservice_client'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashreceipt',
            name='approval_number',
        ),
        migrations.RemoveField(
            model_name='cashreceipt',
            name='transaction_classification',
        ),
        migrations.RemoveField(
            model_name='cashreceipt',
            name='transaction_purpose',
        ),
        migrations.AddField(
            model_name='cashreceipt',
            name='cancel_nts_confirm_date',
            field=models.DateField(blank=True, help_text='취소시 국세청 승인일자', null=True),
        ),
        migrations.AddField(
            model_name='cashreceipt',
            name='cancel_nts_confirm_num',
            field=models.CharField(blank=True, help_text='취소시 국세청 승인번호', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cashreceipt',
            name='cancel_type',
            field=models.CharField(blank=True, help_text='취소사유(거래취소/오류발급/기타)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='cashreceipt',
            name='cash_receipt_type',
            field=models.CharField(choices=[('매출', 'sales'), ('매입', 'purchase')], default='매출', help_text='현금 영수증 유형', max_length=10),
        ),
        migrations.AddField(
            model_name='cashreceipt',
            name='factory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_receipts', to='factory.factory'),
        ),
        migrations.AddField(
            model_name='cashreceipt',
            name='franchise_addr',
            field=models.CharField(blank=True, help_text='가맹점 주소', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='cashreceipt',
            name='franchise_ceo_name',
            field=models.CharField(blank=True, help_text='가맹점 대표자명', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cashreceipt',
            name='franchise_corp_name',
            field=models.CharField(blank=True, help_text='가맹점 상호명', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cashreceipt',
            name='franchise_corp_num',
            field=models.CharField(blank=True, help_text='가맹점 사업자 등록번호', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cashreceipt',
            name='franchise_tel',
            field=models.CharField(blank=True, help_text='가맹점 전화번호', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cashreceipt',
            name='identity_num',
            field=models.CharField(blank=True, help_text='소비자 신분확인번호(사업자번호/주민등록번호/등)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cashreceipt',
            name='item_name',
            field=models.CharField(blank=True, help_text='품목명', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cashreceipt',
            name='nts_confirm_num',
            field=models.CharField(blank=True, help_text='국세청 승인번호', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cashreceipt',
            name='service_charge',
            field=models.IntegerField(default=0, help_text='봉사료'),
        ),
        migrations.AddField(
            model_name='cashreceipt',
            name='trade_method',
            field=models.CharField(blank=True, help_text='거래방법(카드번호, 주민등록번호, 사업자번호, 휴대폰번호)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='cashreceipt',
            name='trade_type',
            field=models.CharField(blank=True, help_text='거래구분(승인거래/취소거래)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='cashreceipt',
            name='trade_usage',
            field=models.CharField(blank=True, help_text='거래용도(소득공제/지출증빙)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='cashreceipt',
            name='user',
            field=models.ForeignKey(blank=True, help_text='사용자', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_receipts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cashreceipt',
            name='client',
            field=models.ForeignKey(blank=True, help_text='거래처', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_receipts', to='factory.factoryclient'),
        ),
    ]
