# Generated by Django 5.0.10 on 2025-08-13 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0005_remove_cashreceipt_approval_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashreceipt',
            name='cash_receipt_type',
            field=models.CharField(choices=[('sales', '매출'), ('purchase', '매입')], default='sales', help_text='현금 영수증 유형', max_length=10),
        ),
        migrations.AlterField(
            model_name='nationaltaxservice',
            name='publish_status',
            field=models.CharField(choices=[('temporary', '임시 저장'), ('pending', '발행 대기'), ('published', '발행 완료')], default='temporary', help_text='발행 상태', max_length=10),
        ),
        migrations.AlterField(
            model_name='nationaltaxservice',
            name='tax_invoice_type',
            field=models.CharField(choices=[('sales', '매출'), ('purchase', '매입')], default='sales', help_text='세금계산서 유형', max_length=10),
        ),
        migrations.AlterField(
            model_name='nationaltaxservice',
            name='transaction_type',
            field=models.CharField(choices=[('receipt', '영수'), ('invoice', '청구')], default='receipt', help_text='거래 유형', max_length=10),
        ),
    ]
