# Generated by Django 5.0.10 on 2025-08-14 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0006_alter_cashreceipt_cash_receipt_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashreceipt',
            name='client_info',
            field=models.JSONField(blank=True, default=dict, help_text='거래처 정보', null=True),
        ),
        migrations.AddField(
            model_name='cashreceipt',
            name='factory_info',
            field=models.JSONField(blank=True, default=dict, help_text='공장 정보', null=True),
        ),
        migrations.AddField(
            model_name='cashreceipt',
            name='products_info',
            field=models.JSONField(blank=True, default=list, help_text='품목 리스트 정보', null=True),
        ),
        migrations.AddField(
            model_name='nationaltaxservice',
            name='client_info',
            field=models.JSONField(blank=True, default=dict, help_text='거래처 정보', null=True),
        ),
        migrations.AddField(
            model_name='nationaltaxservice',
            name='factory_info',
            field=models.JSONField(blank=True, default=dict, help_text='공장 정보', null=True),
        ),
        migrations.AddField(
            model_name='nationaltaxservice',
            name='products_info',
            field=models.JSONField(blank=True, default=list, help_text='품목 리스트 정보', null=True),
        ),
    ]
