# Generated by Django 5.0.10 on 2025-08-23 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0007_cashreceipt_client_info_cashreceipt_factory_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nationaltaxservice',
            name='tax_amount',
            field=models.IntegerField(blank=True, help_text='세액', null=True),
        ),
        migrations.AlterField(
            model_name='nationaltaxservice',
            name='transaction_amount',
            field=models.IntegerField(blank=True, help_text='공급 가액', null=True),
        ),
        migrations.AlterField(
            model_name='nationaltaxservice',
            name='transaction_date',
            field=models.DateField(blank=True, help_text='거래 일자', null=True),
        ),
    ]
