# Generated by Django 5.0.10 on 2025-08-23 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0008_alter_nationaltaxservice_tax_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nationaltaxservice',
            name='publish_status',
            field=models.CharField(choices=[('temporary', '임시 저장'), ('pending', '발행 대기'), ('processing', '처리중'), ('published', '발행 완료'), ('canceled', '발행 취소')], default='temporary', help_text='발행 상태', max_length=10),
        ),
    ]
