# Generated by Django 5.0.10 on 2025-08-23 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0009_alter_nationaltaxservice_publish_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nationaltaxservice',
            name='publish_status',
            field=models.CharField(choices=[('temporary', '임시 저장'), ('pending', '전송 대기'), ('processing', '처리 중'), ('published', '발행 완료'), ('canceled', '발행 취소'), ('failed', '발행 실패')], default='temporary', help_text='발행 상태', max_length=10),
        ),
    ]
