# Generated by Django 5.0.10 on 2025-08-26 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0010_alter_nationaltaxservice_publish_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashreceipt',
            name='product',
        ),
        migrations.RemoveField(
            model_name='cashreceipt',
            name='products_info',
        ),
        migrations.RemoveField(
            model_name='nationaltaxservice',
            name='product',
        ),
        migrations.RemoveField(
            model_name='nationaltaxservice',
            name='products_info',
        ),
    ]
