# Generated by Django 5.0.10 on 2025-12-18 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0023_alter_project_created_at_alter_project_updated_at_and_more'),
        ('tax', '0013_alter_cashreceipt_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxInvoiceAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정일')),
                ('status', models.CharField(choices=[('waiting', '대기'), ('overdue', '연체'), ('partial', '일부'), ('completed', '완료')], default='waiting', help_text='채권/채무 상태', max_length=20)),
                ('invoice_sent_count', models.IntegerField(default=0, help_text='청구서 발송 횟수')),
                ('total_billed_amount', models.IntegerField(help_text='청구금액(합계)')),
                ('outstanding_balance', models.IntegerField(default=0, help_text='미수금액(잔액)')),
                ('collection_terms', models.CharField(blank=True, choices=[('INVOICE_30', '세금계산서 발행 후 30일 이내 입금'), ('INVOICE_EOM_NEXT', '세금계산서 발행 익월 말일 입금'), ('MONTH_END_25_NEXT', '당월 말일 마감, 익월 25일 지급'), ('INSPECTION_30', '검수 완료 후 30일 이내 입금'), ('CUSTOM', '직접 입력')], help_text='수금 조건', max_length=50, null=True)),
                ('collection_terms_custom', models.CharField(blank=True, help_text='수금 조건 직접 입력 (collection_terms가 CUSTOM일 때만 사용)', max_length=200, null=True)),
                ('agreed_payment_date', models.DateField(blank=True, help_text='약정 입금일', null=True)),
                ('notes', models.TextField(blank=True, help_text='특이사항', null=True)),
                ('project', models.ForeignKey(blank=True, help_text='프로젝트', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_invoice_accounts', to='project.project')),
                ('tax_invoice', models.OneToOneField(help_text='세금계산서', on_delete=django.db.models.deletion.CASCADE, related_name='tax_invoice_account', to='tax.nationaltaxservice')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정일')),
                ('payment_date', models.DateField(help_text='입금일/지급일')),
                ('amount_received', models.IntegerField(help_text='받은 금액/지급 금액')),
                ('outstanding_amount_at_payment', models.IntegerField(help_text='미수금액/미지급금액')),
                ('overdue_days', models.IntegerField(default=0, help_text='연체일수')),
                ('tax_invoice_account', models.ForeignKey(help_text='세금계산서 채권/채무', on_delete=django.db.models.deletion.CASCADE, related_name='payment_details', to='tax.taxinvoiceaccount')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
