# Generated by Django 5.0.10 on 2025-12-18 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0014_taxinvoiceaccount_paymentdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxinvoiceaccount',
            name='project',
        ),
    ]
