# Generated by Django 5.0.10 on 2025-12-19 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0015_remove_taxinvoiceaccount_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentdetail',
            name='overdue_days',
        ),
        migrations.AddField(
            model_name='paymentdetail',
            name='expected_payment_date',
            field=models.DateField(blank=True, help_text='입금예정일', null=True),
        ),
    ]
