# Generated by Django 5.0.10 on 2025-12-19 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0016_rename_overdue_days_to_expected_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxinvoiceaccount',
            name='collection_terms',
            field=models.CharField(blank=True, choices=[('INVOICE_30', '세금계산서 발행 후 30일 이내 입금'), ('INVOICE_EOM_NEXT', '세금계산서 발행 익월 말일 입금'), ('CUSTOM', '직접 입력')], help_text='수금 조건', max_length=50, null=True),
        ),
    ]
