# Generated by Django 5.0.10 on 2025-12-19 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0017_remove_collection_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxinvoiceaccount',
            name='cash_receipt',
            field=models.OneToOneField(blank=True, help_text='현금영수증', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cash_receipt_account', to='tax.cashreceipt'),
        ),
        migrations.AlterField(
            model_name='taxinvoiceaccount',
            name='tax_invoice',
            field=models.OneToOneField(blank=True, help_text='세금계산서', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tax_invoice_account', to='tax.nationaltaxservice'),
        ),
    ]
