# Generated by Django 5.0.10 on 2025-12-22 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0018_taxinvoiceaccount_cash_receipt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashreceipt',
            name='is_hidden',
            field=models.BooleanField(default=False, help_text='숨김 여부'),
        ),
    ]
