# Generated by Django 5.0.10 on 2025-06-22 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('factory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정일')),
                ('name', models.CharField(help_text='자재명', max_length=100)),
                ('code', models.CharField(help_text='자재코드', max_length=100)),
                ('unit', models.CharField(help_text='단위', max_length=10)),
                ('spec', models.CharField(help_text='규격', max_length=100)),
                ('current_stock', models.IntegerField(help_text='현재 재고')),
                ('standard_stock', models.IntegerField(help_text='안전 재고')),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factory.factory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정일')),
                ('name', models.CharField(help_text='제품명', max_length=100)),
                ('code', models.CharField(help_text='제품코드', max_length=100)),
                ('unit', models.CharField(help_text='단위', max_length=10)),
                ('spec', models.CharField(help_text='규격', max_length=100)),
                ('current_stock', models.IntegerField(help_text='현재 재고')),
                ('average_production_time', models.IntegerField(blank=True, help_text='평균 생산 시간 (초 단위)', null=True)),
                ('buffer_rate', models.DecimalField(decimal_places=2, help_text='재고 버퍼 비율', max_digits=5)),
                ('location', models.CharField(blank=True, help_text='위치', max_length=100, null=True)),
                ('note', models.TextField(blank=True, help_text='특이사항', null=True)),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factory.factory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MaterialProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정일')),
                ('quantity', models.DecimalField(decimal_places=2, help_text='제품 1개 생산에 필요한 원자재 수량', max_digits=10)),
                ('material', models.ForeignKey(help_text='원자재', on_delete=django.db.models.deletion.CASCADE, to='stock.material')),
                ('product', models.ForeignKey(help_text='제품', on_delete=django.db.models.deletion.CASCADE, to='stock.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='material',
            name='products',
            field=models.ManyToManyField(help_text='이 원자재로 만들 수 있는 품목들', related_name='materials', through='stock.MaterialProduct', to='stock.product'),
        ),
    ]
