# Generated by Django 5.0.10 on 2025-07-15 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('factory', '0001_initial'),
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정일')),
                ('type', models.CharField(choices=[('구매', 'purchase'), ('소모', 'consumption')], default='구매', max_length=10)),
                ('quantity', models.IntegerField(help_text='재고 변동 수량')),
                ('price', models.IntegerField(blank=True, help_text='구매 단가 (원자재 구매 시에만 입력)', null=True)),
                ('total_stock', models.IntegerField(help_text='재고 변동 후 재고')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MaterialProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정일')),
                ('quantity', models.DecimalField(decimal_places=2, help_text='제품 1개 생산에 필요한 원자재 수량', max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정일')),
                ('name', models.CharField(help_text='제품명', max_length=100)),
                ('code', models.CharField(help_text='제품코드', max_length=100)),
                ('unit', models.CharField(help_text='단위', max_length=10)),
                ('spec', models.CharField(help_text='규격', max_length=100)),
                ('current_stock', models.IntegerField(default=0, help_text='현재 재고')),
                ('average_production_time', models.IntegerField(blank=True, help_text='평균 생산 시간 (초 단위)', null=True)),
                ('buffer_rate', models.DecimalField(decimal_places=2, default=0.1, help_text='재고 버퍼 비율 (기본값: 10%)', max_digits=5)),
                ('note', models.TextField(blank=True, help_text='특이사항', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정일')),
                ('type', models.CharField(choices=[('입고', 'in'), ('출고', 'out')], default='입고', max_length=10)),
                ('quantity', models.IntegerField(help_text='재고 변동 수량')),
                ('total_stock', models.IntegerField(help_text='재고 변동 후 재고')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정일')),
                ('name', models.CharField(help_text='자재명', max_length=100)),
                ('code', models.CharField(help_text='자재코드', max_length=100)),
                ('unit', models.CharField(help_text='단위', max_length=10)),
                ('spec', models.CharField(help_text='규격', max_length=100)),
                ('current_stock', models.IntegerField(default=0, help_text='현재 재고')),
                ('standard_stock', models.IntegerField(default=0, help_text='안전 재고')),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='factory.factory')),
                ('location', models.ManyToManyField(blank=True, help_text='위치', related_name='materials', to='location.location')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
