# Generated by Django 5.0.10 on 2025-07-08 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='location',
            field=models.ForeignKey(blank=True, help_text='위치', null=True, on_delete=django.db.models.deletion.CASCADE, to='location.location'),
        ),
    ]
