# Generated by Django 5.0.10 on 2025-07-15 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('factory', '0001_initial'),
        ('location', '0001_initial'),
        ('stock', '0001_initial'),
        ('tax', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialhistory',
            name='cash_receipt',
            field=models.ForeignKey(blank=True, help_text='현금영수증', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='material_histories', to='tax.cashreceipt'),
        ),
        migrations.AddField(
            model_name='materialhistory',
            name='client',
            field=models.ForeignKey(help_text='고객', on_delete=django.db.models.deletion.CASCADE, related_name='material_histories', to='factory.factoryclient'),
        ),
        migrations.AddField(
            model_name='materialhistory',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='stock.material'),
        ),
        migrations.AddField(
            model_name='materialhistory',
            name='purchase_tax_invoice',
            field=models.ForeignKey(blank=True, help_text='구매 세금계산서', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='material_histories', to='tax.nationaltaxservice'),
        ),
        migrations.AddField(
            model_name='materialproduct',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_products', to='stock.material'),
        ),
        migrations.AddField(
            model_name='product',
            name='factory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='factory.factory'),
        ),
        migrations.AddField(
            model_name='product',
            name='location',
            field=models.ManyToManyField(blank=True, help_text='위치', related_name='products', to='location.location'),
        ),
        migrations.AddField(
            model_name='materialproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_products', to='stock.product'),
        ),
        migrations.AddField(
            model_name='producthistory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='stock.product'),
        ),
        migrations.AlterUniqueTogether(
            name='material',
            unique_together={('factory', 'code')},
        ),
    ]
