# Generated by Django 5.0.10 on 2025-07-07 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('factory', '0001_initial'),
        ('location', '0001_initial'),
        ('stock', '0001_initial'),
        ('tax', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialhistory',
            name='cash_receipt',
            field=models.ForeignKey(blank=True, help_text='현금영수증', null=True, on_delete=django.db.models.deletion.CASCADE, to='tax.cashreceipt'),
        ),
        migrations.AddField(
            model_name='materialhistory',
            name='client',
            field=models.ForeignKey(help_text='고객', on_delete=django.db.models.deletion.CASCADE, to='factory.factoryclient'),
        ),
        migrations.AddField(
            model_name='materialhistory',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.material'),
        ),
        migrations.AddField(
            model_name='materialhistory',
            name='purchase_tax_invoice',
            field=models.ForeignKey(blank=True, help_text='구매 세금계산서', null=True, on_delete=django.db.models.deletion.CASCADE, to='tax.nationaltaxservice'),
        ),
        migrations.AddField(
            model_name='materialproduct',
            name='material',
            field=models.ForeignKey(help_text='원자재', on_delete=django.db.models.deletion.CASCADE, to='stock.material'),
        ),
        migrations.AddField(
            model_name='product',
            name='factory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factory.factory'),
        ),
        migrations.AddField(
            model_name='product',
            name='location',
            field=models.ForeignKey(blank=True, help_text='위치', null=True, on_delete=django.db.models.deletion.CASCADE, to='location.location'),
        ),
        migrations.AddField(
            model_name='materialproduct',
            name='product',
            field=models.ForeignKey(help_text='제품', on_delete=django.db.models.deletion.CASCADE, to='stock.product'),
        ),
        migrations.AddField(
            model_name='material',
            name='products',
            field=models.ManyToManyField(blank=True, help_text='이 원자재로 만들 수 있는 품목들 (선택사항)', related_name='materials', through='stock.MaterialProduct', to='stock.product'),
        ),
        migrations.AddField(
            model_name='producthistory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.product'),
        ),
    ]
