# Generated by Django 5.0.10 on 2025-07-02 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0001_initial'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='current_stock',
            field=models.IntegerField(default=0, help_text='현재 재고'),
        ),
        migrations.AlterField(
            model_name='material',
            name='products',
            field=models.ManyToManyField(blank=True, help_text='이 원자재로 만들 수 있는 품목들 (선택사항)', related_name='materials', through='stock.MaterialProduct', to='stock.product'),
        ),
        migrations.AlterField(
            model_name='material',
            name='standard_stock',
            field=models.IntegerField(default=0, help_text='안전 재고'),
        ),
        migrations.AlterField(
            model_name='product',
            name='buffer_rate',
            field=models.DecimalField(decimal_places=2, default=0.1, help_text='재고 버퍼 비율 (기본값: 10%)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='current_stock',
            field=models.IntegerField(default=0, help_text='현재 재고'),
        ),
        migrations.CreateModel(
            name='MaterialHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정일')),
                ('type', models.CharField(choices=[('구매', 'purchase'), ('소모', 'consumption')], default='구매', max_length=10)),
                ('quantity', models.IntegerField(help_text='재고 변동 수량')),
                ('price', models.IntegerField(blank=True, help_text='구매 단가 (원자재 구매 시에만 입력)', null=True)),
                ('total_stock', models.IntegerField(help_text='재고 변동 후 재고')),
                ('client', models.ForeignKey(help_text='고객', on_delete=django.db.models.deletion.CASCADE, to='factory.factoryclient')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.material')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
