# Generated by Django 5.0.10 on 2025-07-08 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
        ('stock', '0002_material_location'),
        ('tax', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialhistory',
            name='cash_receipt',
            field=models.ForeignKey(blank=True, help_text='현금영수증', null=True, on_delete=django.db.models.deletion.CASCADE, to='tax.cashreceipt'),
        ),
        migrations.AddField(
            model_name='materialhistory',
            name='purchase_tax_invoice',
            field=models.ForeignKey(blank=True, help_text='구매 세금계산서', null=True, on_delete=django.db.models.deletion.CASCADE, to='tax.nationaltaxservice'),
        ),
        migrations.AlterField(
            model_name='product',
            name='location',
            field=models.ForeignKey(blank=True, help_text='위치', null=True, on_delete=django.db.models.deletion.CASCADE, to='location.location'),
        ),
    ]
