# Generated by Django 5.2.4 on 2025-08-01 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='current_stock',
            field=models.IntegerField(default=0, help_text='현재 재고', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='current_stock',
            field=models.IntegerField(default=0, help_text='현재 재고', null=True),
        ),
    ]
