# Generated by Django 5.0.10 on 2025-07-09 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0004_alter_factory_owner_alter_factoryclient_factory_and_more'),
        ('location', '0001_initial'),
        ('stock', '0003_materialhistory_cash_receipt_and_more'),
        ('tax', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='material',
            unique_together={('factory', 'code')},
        ),
        migrations.AlterField(
            model_name='material',
            name='factory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='factory.factory'),
        ),
        migrations.AlterField(
            model_name='material',
            name='location',
            field=models.ForeignKey(blank=True, help_text='위치', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='location.location'),
        ),
        migrations.AlterField(
            model_name='materialhistory',
            name='cash_receipt',
            field=models.ForeignKey(blank=True, help_text='현금영수증', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='material_histories', to='tax.cashreceipt'),
        ),
        migrations.AlterField(
            model_name='materialhistory',
            name='client',
            field=models.ForeignKey(help_text='고객', on_delete=django.db.models.deletion.CASCADE, related_name='material_histories', to='factory.factoryclient'),
        ),
        migrations.AlterField(
            model_name='materialhistory',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='stock.material'),
        ),
        migrations.AlterField(
            model_name='materialhistory',
            name='purchase_tax_invoice',
            field=models.ForeignKey(blank=True, help_text='구매 세금계산서', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='material_histories', to='tax.nationaltaxservice'),
        ),
        migrations.AlterField(
            model_name='materialproduct',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_products', to='stock.material'),
        ),
        migrations.AlterField(
            model_name='materialproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_products', to='stock.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='factory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='factory.factory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='location',
            field=models.ForeignKey(blank=True, help_text='위치', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='location.location'),
        ),
        migrations.AlterField(
            model_name='producthistory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='stock.product'),
        ),
        migrations.RemoveField(
            model_name='material',
            name='products',
        ),
    ]
