# Generated by Django 5.0.10 on 2025-08-13 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_alter_material_current_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialhistory',
            name='type',
            field=models.CharField(choices=[('purchase', '구매'), ('consumption', '소모')], default='purchase', max_length=20),
        ),
        migrations.AlterField(
            model_name='producthistory',
            name='type',
            field=models.CharField(choices=[('in', '입고'), ('out', '출고')], default='in', max_length=10),
        ),
    ]
