# Generated by Django 5.0.10 on 2025-08-15 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_alter_materialhistory_type_alter_producthistory_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='cost_average',
            field=models.PositiveIntegerField(default=0, help_text='평균 단가'),
        ),
    ]
