# Generated by Django 5.0.10 on 2025-07-11 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
        ('stock', '0004_alter_material_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='location',
        ),
        migrations.RemoveField(
            model_name='product',
            name='location',
        ),
        migrations.AddField(
            model_name='material',
            name='location',
            field=models.ManyToManyField(blank=True, help_text='위치', related_name='materials', to='location.location'),
        ),
        migrations.AddField(
            model_name='product',
            name='location',
            field=models.ManyToManyField(blank=True, help_text='위치', related_name='products', to='location.location'),
        ),
    ]
