# Generated by Django 5.0.10 on 2025-08-26 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_material_cost_average'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialhistory',
            name='cash_receipt',
        ),
        migrations.RemoveField(
            model_name='materialhistory',
            name='purchase_tax_invoice',
        ),
    ]
