# Generated by Django 5.0.10 on 2025-08-27 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_remove_materialhistory_cash_receipt_and_more'),
        ('tax', '0011_remove_cashreceipt_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialhistory',
            name='cash_receipt',
            field=models.ForeignKey(blank=True, help_text='연결된 현금영수증', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_histories', to='tax.cashreceipt'),
        ),
    ]
