# Generated by Django 5.0.10 on 2025-09-22 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_materialhistory_cash_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='producthistory',
            name='processing_date',
            field=models.DateField(default='2025-09-20', help_text='처리일자 (입고: 생산마감일자, 출고: 납품일자)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producthistory',
            name='source_id',
            field=models.PositiveIntegerField(blank=True, help_text='입고: plan_id, 출고: quotation_product_id', null=True),
        ),
    ]
