# Generated by Django 5.0.10 on 2025-09-22 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_producthistory_processing_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producthistory',
            name='processing_date',
        ),
        migrations.RemoveField(
            model_name='producthistory',
            name='source_id',
        ),
        migrations.RemoveField(
            model_name='producthistory',
            name='type',
        ),
        migrations.AddField(
            model_name='producthistory',
            name='client_name',
            field=models.CharField(blank=True, help_text='해당 history가 발생한 프로젝트의 거래처명', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='producthistory',
            name='delivery_quantity',
            field=models.IntegerField(blank=True, help_text='납품 수량', null=True),
        ),
        migrations.AddField(
            model_name='producthistory',
            name='is_canceled',
            field=models.BooleanField(default=False, help_text='취소 여부'),
        ),
        migrations.AddField(
            model_name='producthistory',
            name='production_quantity',
            field=models.IntegerField(blank=True, help_text='생산 수량', null=True),
        ),
        migrations.AddField(
            model_name='producthistory',
            name='project_id',
            field=models.PositiveIntegerField(blank=True, help_text='해당 history가 발생한 project_id', null=True),
        ),
        migrations.AlterField(
            model_name='producthistory',
            name='quantity',
            field=models.IntegerField(help_text='재고 변동 수량 (음수 & 양수), 취소 된 history에 대한 재고 반영'),
        ),
    ]
