# Generated by Django 5.0.10 on 2025-10-03 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0010_remove_factory_is_trial'),
        ('stock', '0009_remove_producthistory_processing_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialhistory',
            name='client',
            field=models.ForeignKey(blank=True, help_text='고객 (원자재 구매 시에만 입력)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_histories', to='factory.factoryclient'),
        ),
    ]
