# Generated by Django 5.0.10 on 2025-11-21 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0010_alter_materialhistory_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='cost_average',
        ),
        migrations.AddField(
            model_name='materialhistory',
            name='expiration_date',
            field=models.DateField(blank=True, help_text='유통기한', null=True),
        ),
        migrations.AddField(
            model_name='materialhistory',
            name='lot_number',
            field=models.CharField(blank=True, default='', help_text='LOT 번호', max_length=100),
        ),
        migrations.AddField(
            model_name='materialhistory',
            name='remaining_quantity',
            field=models.IntegerField(blank=True, help_text='현재 잔량', null=True),
        ),
        migrations.AddField(
            model_name='materialhistory',
            name='warehouse_location',
            field=models.CharField(blank=True, help_text='창고 위치', max_length=100, null=True),
        ),
    ]
