# Generated by Django 5.0.10 on 2025-11-21 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0011_remove_material_cost_average_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='buffer_rate',
            field=models.DecimalField(decimal_places=2, default=0.1, help_text='재고 불량률 (기본값: 10%)', max_digits=5),
        ),
    ]
