# Generated by Django 5.0.10 on 2025-11-23 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0012_alter_product_buffer_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='expiry_days',
            field=models.IntegerField(default=7, help_text='유통기한 (일)'),
        ),
        migrations.AddField(
            model_name='material',
            name='max_stock',
            field=models.IntegerField(blank=True, help_text='최대 재고', null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='memo',
            field=models.TextField(blank=True, help_text='메모', null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='rop',
            field=models.IntegerField(blank=True, help_text='재주문점 (Reorder Point)', null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='standard_stock',
            field=models.IntegerField(blank=True, help_text='안전 재고', null=True),
        ),
    ]
