# Generated by Django 5.0.10 on 2025-11-23 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0013_material_expiry_days_material_max_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='expiry_days',
            field=models.IntegerField(blank=True, default=7, help_text='유통기한 (일)', null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='max_stock',
            field=models.IntegerField(blank=True, help_text='적정 재고(최대 재고)', null=True),
        ),
    ]
