# Generated by Django 5.0.10 on 2025-11-27 07:59

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0014_alter_material_expiry_days_alter_material_max_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='current_stock',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='현재 재고', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='max_stock',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='적정 재고(최대 재고)', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='rop',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='재주문점 (Reorder Point)', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='standard_stock',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='안전 재고', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='materialhistory',
            name='quantity',
            field=models.DecimalField(decimal_places=2, help_text='재고 변동 수량', max_digits=12),
        ),
        migrations.AlterField(
            model_name='materialhistory',
            name='remaining_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='현재 잔량', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='materialhistory',
            name='total_stock',
            field=models.DecimalField(decimal_places=2, help_text='재고 변동 후 재고', max_digits=12),
        ),
    ]
