# Generated by Django 5.0.10 on 2025-12-12 21:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0016_materialusage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materialusage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Material Usage', 'verbose_name_plural': 'Material Usages'},
        ),
        migrations.AlterField(
            model_name='material',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='생성일'),
        ),
        migrations.AlterField(
            model_name='material',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='수정일'),
        ),
        migrations.AlterField(
            model_name='materialhistory',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='생성일'),
        ),
        migrations.AlterField(
            model_name='materialhistory',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='수정일'),
        ),
        migrations.AlterField(
            model_name='materialproduct',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='생성일'),
        ),
        migrations.AlterField(
            model_name='materialproduct',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='수정일'),
        ),
        migrations.AlterField(
            model_name='materialusage',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='생성일'),
        ),
        migrations.AlterField(
            model_name='materialusage',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='수정일'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='생성일'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='수정일'),
        ),
        migrations.AlterField(
            model_name='producthistory',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='생성일'),
        ),
        migrations.AlterField(
            model_name='producthistory',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='수정일'),
        ),
    ]
