# Generated by Django 5.0.10 on 2025-12-18 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0017_alter_materialusage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='생성일'),
        ),
        migrations.AlterField(
            model_name='material',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='수정일'),
        ),
        migrations.AlterField(
            model_name='materialhistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='생성일'),
        ),
        migrations.AlterField(
            model_name='materialhistory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='수정일'),
        ),
        migrations.AlterField(
            model_name='materialproduct',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='생성일'),
        ),
        migrations.AlterField(
            model_name='materialproduct',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='수정일'),
        ),
        migrations.AlterField(
            model_name='materialusage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='생성일'),
        ),
        migrations.AlterField(
            model_name='materialusage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='수정일'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='생성일'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='수정일'),
        ),
        migrations.AlterField(
            model_name='producthistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='생성일'),
        ),
        migrations.AlterField(
            model_name='producthistory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='수정일'),
        ),
    ]
