# Generated by Django 5.0.10 on 2026-01-12 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0018_alter_material_created_at_alter_material_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='expiry_days',
            field=models.IntegerField(blank=True, default=None, help_text='유통기한 (일)', null=True),
        ),
    ]
