# Generated by Django 5.0.10 on 2026-08-13 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0014_factorymember_dashboard_layout'),
        ('stock', '0019_alter_material_expiry_days'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('factory', 'code')},
        ),
    ]
