version: "3.3"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks:
      - network
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    networks:
      - network
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - network
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    networks:
      - network
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./backend/local-cdn:/app/backend/local-cdn
    depends_on:
      - frontend
      - backend

networks:
  network:


volumes:
  redis_data:
