# Generated by Django 5.0.10 on 2025-06-17 05:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(help_text='설비상태', max_length=50)),
                ('name', models.CharField(help_text='설비명', max_length=100)),
                ('type', models.CharField(help_text='설비유형', max_length=50)),
                ('location', models.CharField(help_text='위치', max_length=100)),
                ('special_notes', models.TextField(blank=True, help_text='특이사항', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('production_time_per_unit', models.FloatField(help_text='단위당 생산시간(분)')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.equipment')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.item')),
            ],
            options={
                'verbose_name': '설비별 생산품목',
                'verbose_name_plural': '설비별 생산품목',
                'unique_together': {('equipment', 'item')},
            },
        ),
        migrations.AddField(
            model_name='equipment',
            name='producible_items',
            field=models.ManyToManyField(blank=True, help_text='생산가능품목', related_name='equipments', through='equipment.EquipmentItem', to='item.item'),
        ),
    ]
