# Generated by Django 5.0.10 on 2025-06-17 05:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='자재명', max_length=100)),
                ('code', models.CharField(help_text='자재코드', max_length=50, unique=True)),
                ('specification', models.CharField(help_text='규격', max_length=100)),
                ('unit', models.CharField(help_text='단위', max_length=20)),
                ('current_stock', models.PositiveIntegerField(default=0, help_text='현재 재고')),
                ('min_stock', models.PositiveIntegerField(default=0, help_text='최소재고')),
                ('expiration_date', models.DateField(blank=True, help_text='유통기한', null=True)),
                ('received_date', models.DateField(help_text='입고일자')),
                ('warehouse_location', models.CharField(help_text='창고위치', max_length=100)),
            ],
        ),
    ]
