# Generated by Django 5.0.10 on 2025-07-07 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('document', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정일')),
                ('type', models.CharField(choices=[('계획 변경', 'plan'), ('메모', 'memo'), ('반품', 'refund')], default='계획 변경', max_length=10)),
                ('title', models.CharField(help_text='로그 제목', max_length=100)),
                ('content', models.TextField(help_text='로그 내용')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정일')),
                ('status', models.CharField(choices=[('가동 대기', 'pending'), ('가동 중', 'production'), ('가동 완료', 'completed'), ('가동 불가', 'impossible')], default='가동 대기', max_length=10)),
                ('quantity', models.IntegerField(help_text='생산 수량')),
                ('start_date', models.DateField(help_text='생산 일자')),
                ('end_date', models.DateField(help_text='마감 예정 일자')),
                ('avg_production_time', models.IntegerField(help_text='평균 생산 시간(초)')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정일')),
                ('amount', models.IntegerField(help_text='반품 수량')),
                ('refund_date', models.DateField(help_text='반품 일자')),
                ('current_stock', models.IntegerField(help_text='현재 재고')),
                ('production_amount', models.IntegerField(blank=True, help_text='생산 수량', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정일')),
                ('status', models.CharField(choices=[('견적 협의중', 'quotation'), ('생산 대기', 'pending'), ('생산 중', 'production'), ('생산 완료', 'manufactured'), ('납품', 'delivery'), ('프로젝트 완료', 'completed')], default='견적 협의중', max_length=10)),
                ('transact_date', models.DateField(blank=True, help_text='거래명세서 발행 일자', null=True)),
                ('quotation', models.ForeignKey(help_text='견적서', on_delete=django.db.models.deletion.CASCADE, to='document.quotation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
