# Generated by Django 5.0.10 on 2025-06-17 05:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(help_text='진행상태', max_length=50)),
                ('execution_date', models.DateField(help_text='집행일자')),
                ('due_date', models.DateField(help_text='납기일자')),
                ('completed_date', models.DateField(blank=True, help_text='완료일자', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation_status', models.CharField(help_text='가동상태', max_length=50)),
                ('equipment', models.ForeignKey(help_text='연결된 설비', on_delete=django.db.models.deletion.CASCADE, related_name='project_items', to='equipment.equipment')),
                ('item', models.ForeignKey(help_text='연결된 품목', on_delete=django.db.models.deletion.CASCADE, related_name='project_items', to='item.item')),
                ('project', models.ForeignKey(help_text='연결된 프로젝트', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='project.project')),
            ],
        ),
    ]
