# Generated by Django 5.0.10 on 2025-07-15 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('document', '0004_initial'),
        ('factory', '0001_initial'),
        ('project', '0001_initial'),
        ('stock', '0001_initial'),
        ('tax', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tax_invoice',
            field=models.ForeignKey(blank=True, help_text='세금계산서', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='tax.nationaltaxservice'),
        ),
        migrations.AddField(
            model_name='projectlog',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='project.project'),
        ),
        migrations.AddField(
            model_name='projectplan',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='factory.factoryequipment'),
        ),
        migrations.AddField(
            model_name='projectplan',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='document.quotationproduct'),
        ),
        migrations.AddField(
            model_name='projectplan',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='project.project'),
        ),
        migrations.AddField(
            model_name='refund',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='stock.product'),
        ),
        migrations.AddField(
            model_name='refund',
            name='project_log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='project.projectlog'),
        ),
    ]
