# Generated by Django 5.0.10 on 2025-07-02 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='financial_document',
        ),
        migrations.AddField(
            model_name='project',
            name='is_transaction_publish',
            field=models.BooleanField(default=False, help_text='거래명세서 발행 여부'),
        ),
        migrations.AddField(
            model_name='project',
            name='tax_invoice_date',
            field=models.DateField(blank=True, help_text='세금계산서 발행 일자', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='tax_invoice_status',
            field=models.CharField(choices=[('미발행', 'pending'), ('발행 중', 'processing'), ('발행 완료', 'completed')], default='미발행', help_text='세금계산서 발행 상태', max_length=10),
        ),
        migrations.AddField(
            model_name='project',
            name='transact_date',
            field=models.DateField(blank=True, help_text='거래명세서 발행 일자', null=True),
        ),
    ]
