# Generated by Django 5.0.10 on 2025-07-08 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정일')),
                ('amount', models.IntegerField(help_text='반품 수량')),
                ('refund_date', models.DateField(help_text='반품 일자')),
                ('current_stock', models.IntegerField(help_text='현재 재고')),
                ('production_amount', models.IntegerField(blank=True, help_text='생산 수량', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='project',
            name='is_transaction_publish',
        ),
        migrations.RemoveField(
            model_name='project',
            name='tax_invoice_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='tax_invoice_status',
        ),
    ]
