# Generated by Django 5.0.10 on 2025-07-08 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_refund_remove_project_is_transaction_publish_and_more'),
        ('stock', '0002_material_location'),
        ('tax', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tax_invoice',
            field=models.ForeignKey(blank=True, help_text='세금계산서', null=True, on_delete=django.db.models.deletion.CASCADE, to='tax.nationaltaxservice'),
        ),
        migrations.AddField(
            model_name='refund',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.product'),
        ),
        migrations.AddField(
            model_name='refund',
            name='project_log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.projectlog'),
        ),
    ]
