# Generated by Django 5.0.10 on 2025-07-09 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0004_remove_quotation_products_quotation_project_and_more'),
        ('factory', '0004_alter_factory_owner_alter_factoryclient_factory_and_more'),
        ('project', '0003_project_tax_invoice_refund_product_and_more'),
        ('stock', '0003_materialhistory_cash_receipt_and_more'),
        ('tax', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='quotation',
        ),
        migrations.AlterField(
            model_name='project',
            name='tax_invoice',
            field=models.ForeignKey(blank=True, help_text='세금계산서', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='tax.nationaltaxservice'),
        ),
        migrations.AlterField(
            model_name='projectlog',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='project.project'),
        ),
        migrations.AlterField(
            model_name='projectplan',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='factory.factoryequipment'),
        ),
        migrations.AlterField(
            model_name='projectplan',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='document.quotationproduct'),
        ),
        migrations.AlterField(
            model_name='projectplan',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='project.project'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='stock.product'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='project_log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='project.projectlog'),
        ),
    ]
