# Generated by Django 5.2.4 on 2025-08-04 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('견적 협의중', 'quotation'), ('주문 확정', 'confirmed'), ('생산 대기', 'pending'), ('생산 중', 'production'), ('생산 완료', 'manufactured'), ('납품', 'delivery'), ('프로젝트 완료', 'completed'), ('중단', 'suspended')], default='견적 협의중', max_length=10),
        ),
    ]
