# Generated by Django 5.0.10 on 2025-08-08 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectplan',
            name='is_completed',
            field=models.BooleanField(blank=True, default=False, help_text='생산 완료 여부', null=True),
        ),
        migrations.AddField(
            model_name='projectplan',
            name='is_refunded',
            field=models.BooleanField(blank=True, default=False, help_text='반품 여부', null=True),
        ),
    ]
