# Generated by Django 5.0.10 on 2025-08-13 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_projectplan_is_completed_projectplan_is_refunded'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_refunded',
            field=models.BooleanField(default=False, help_text='반품 여부'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('quotation', '견적 협의중'), ('confirmed', '주문 확정'), ('pending', '생산 대기'), ('production', '생산 중'), ('manufactured', '생산 완료'), ('delivery', '납품'), ('completed', '프로젝트 완료'), ('suspended', '중단')], default='quotation', max_length=20),
        ),
        migrations.AlterField(
            model_name='projectlog',
            name='type',
            field=models.CharField(choices=[('plan', '계획 변경'), ('memo', '메모'), ('refund', '반품')], default='plan', max_length=20),
        ),
        migrations.AlterField(
            model_name='projectplan',
            name='status',
            field=models.CharField(choices=[('pending', '가동 대기'), ('production', '가동 중'), ('completed', '가동 완료'), ('impossible', '가동 불가')], default='pending', max_length=20),
        ),
    ]
