# Generated by Django 5.0.10 on 2025-08-13 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_project_is_refunded_alter_project_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectplan',
            name='is_refunded',
        ),
        migrations.AddField(
            model_name='refund',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='project.projectplan'),
        ),
    ]
