# Generated by Django 5.0.10 on 2025-08-13 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_remove_projectplan_is_refunded_refund_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='name',
            field=models.CharField(blank=True, help_text='프로젝트명', max_length=50, null=True),
        ),
    ]
