# Generated by Django 5.0.10 on 2025-08-13 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_project_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refund',
            name='project_log',
        ),
        migrations.AddField(
            model_name='projectlog',
            name='refund',
            field=models.ForeignKey(blank=True, help_text='반품 정보', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='project.refund'),
        ),
    ]
