# Generated by Django 5.0.10 on 2025-08-14 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_remove_refund_project_log_projectlog_refund'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectplan',
            name='end_date',
            field=models.DateTimeField(help_text='마감 예정 일시'),
        ),
        migrations.AlterField(
            model_name='projectplan',
            name='start_date',
            field=models.DateTimeField(help_text='생산 시작 일시'),
        ),
    ]
