# Generated by Django 5.0.10 on 2025-08-16 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_alter_projectplan_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectplan',
            name='end_notification',
            field=models.BooleanField(default=False, help_text='생산 완료 알림 여부'),
        ),
    ]
