# Generated by Django 5.0.10 on 2025-08-23 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_projectplan_end_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectplan',
            name='is_completed',
        ),
    ]
