# Generated by Django 5.0.10 on 2025-08-26 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_remove_projectplan_is_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectlog',
            name='type',
            field=models.CharField(choices=[('date', '생산 일자 변경'), ('equipment', '생산 설비 변경'), ('memo', '메모'), ('refund', '반품')], default='date', max_length=20),
        ),
    ]
