# Generated by Django 5.0.10 on 2025-09-08 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_alter_projectlog_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='printed_at',
            field=models.DateTimeField(blank=True, help_text='거래명세서 출력 일시', null=True),
        ),
    ]
