# Generated by Django 5.0.10 on 2025-09-08 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_project_printed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, help_text='주문 확정 일시', null=True),
        ),
    ]
