# Generated by Django 5.0.10 on 2025-10-01 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0015_project_confirmed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='confirmed_at',
            field=models.DateField(blank=True, help_text='주문 확정 일자', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='printed_at',
            field=models.DateField(blank=True, help_text='거래명세서 출력 일자', null=True),
        ),
    ]
