# Generated by Django 5.0.10 on 2025-10-04 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0016_alter_project_confirmed_at_alter_project_printed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectplan',
            name='material_consumed',
            field=models.BooleanField(default=False, help_text='해당 생산 계획에 대한 원자재 소모 처리가 완료되었는지 여부'),
        ),
    ]
