# Generated by Django 5.0.10 on 2025-11-18 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0017_projectplan_material_consumed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='confirmed_at',
            new_name='pending_at',
        ),
    ]
