# Generated by Django 5.0.10 on 2025-11-18 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0018_rename_confirmed_at_project_pending_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='confirmed_at',
            field=models.DateField(blank=True, help_text='견적서 -> 주문 확정 일자', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='pending_at',
            field=models.DateField(blank=True, help_text='주문 확정 -> 생산 대기 일자', null=True),
        ),
    ]
