# Generated by Django 5.0.10 on 2025-11-20 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0019_project_confirmed_at_alter_project_pending_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectplan',
            name='defective_quantity',
            field=models.IntegerField(null=True, blank=True, help_text='불량품 수량'),
        ),
    ]
