# Generated by Django 5.0.10 on 2025-12-03 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0020_projectplan_defective_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectlog',
            name='type',
            field=models.CharField(choices=[('date', '생산 일자 변경'), ('equipment', '생산 설비 변경'), ('quantity', '생산 수량 변경'), ('memo', '메모'), ('refund', '반품')], default='date', max_length=20),
        ),
        migrations.AlterField(
            model_name='projectplan',
            name='avg_production_time',
            field=models.IntegerField(blank=True, help_text='평균 생산 시간(초)', null=True),
        ),
    ]
