# Generated by Django 5.0.10 on 2025-11-27 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0020_projectplan_defective_quantity'),
        ('repackaging', '0001_initial'),
        ('stock', '0014_alter_material_expiry_days_alter_material_max_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPlanMaterialUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정일')),
                ('usage_amount', models.DecimalField(decimal_places=2, help_text='실제 투입량', max_digits=10)),
                ('material', models.ForeignKey(help_text='실제 사용한 자재 ID (대체 자재일 수도 있음)', on_delete=django.db.models.deletion.CASCADE, related_name='plan_usages', to='stock.material')),
                ('material_history', models.ForeignKey(blank=True, help_text='사용한 자재 이력 (MaterialHistory 또는 MaterialRepackaging 중 하나만 설정)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_usages', to='stock.materialhistory')),
                ('material_repackaging', models.ForeignKey(blank=True, help_text='사용한 자재 소분 내역 (MaterialHistory 또는 MaterialRepackaging 중 하나만 설정)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_usages', to='repackaging.materialrepackaging')),
                ('original_material', models.ForeignKey(blank=True, help_text='원래 계획된 자재 ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='original_plan_usages', to='stock.material')),
                ('plan', models.ForeignKey(help_text='생산 계획', on_delete=django.db.models.deletion.CASCADE, related_name='material_usages', to='project.projectplan')),
            ],
            options={
                'verbose_name': '프로젝트 플랜 자재 사용 내역',
                'verbose_name_plural': '프로젝트 플랜 자재 사용 내역',
                'ordering': ['-created_at'],
            },
        ),
    ]
