# Generated by Django 5.0.10 on 2025-12-12 21:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0021_alter_projectlog_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='생성일'),
        ),
        migrations.AlterField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='수정일'),
        ),
        migrations.AlterField(
            model_name='projectlog',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='생성일'),
        ),
        migrations.AlterField(
            model_name='projectlog',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='수정일'),
        ),
        migrations.AlterField(
            model_name='projectplan',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='생성일'),
        ),
        migrations.AlterField(
            model_name='projectplan',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='수정일'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='생성일'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='수정일'),
        ),
    ]
