# Generated by Django 5.0.10 on 2026-06-23 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0023_alter_project_created_at_alter_project_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='completed_at',
            field=models.DateField(blank=True, help_text='프로젝트 완료 일자', null=True),
        ),
    ]
