# Generated by Django 5.0.10 on 2025-06-22 07:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정일')),
                ('name', models.CharField(help_text='팩토리 이름', max_length=100)),
                ('business_registration_number', models.CharField(blank=True, help_text='사업자등록번호 (예: 123-45-67890)', max_length=12, null=True)),
                ('representative_name', models.CharField(blank=True, help_text='대표자명', max_length=50, null=True)),
                ('manager_email', models.EmailField(blank=True, help_text='담당자 이메일', max_length=100, null=True)),
                ('manager_phone', models.CharField(blank=True, help_text='담당자 연락처', max_length=15, null=True)),
                ('manager_fax', models.CharField(blank=True, help_text='담당자 팩스번호', max_length=15, null=True)),
                ('business_type', models.CharField(blank=True, help_text='업태', max_length=100, null=True)),
                ('business_category', models.CharField(blank=True, help_text='종목', max_length=100, null=True)),
                ('business_address', models.TextField(blank=True, help_text='사업장 주소', null=True)),
                ('is_trial', models.BooleanField(default=False, help_text='트라이얼 여부')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FactoryClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정일')),
                ('name', models.CharField(help_text='회사명', max_length=100)),
                ('business_registration_number', models.CharField(blank=True, help_text='사업자등록번호 (예: 123-45-67890)', max_length=12, null=True)),
                ('representative_name', models.CharField(blank=True, help_text='대표자명', max_length=50, null=True)),
                ('email', models.EmailField(blank=True, help_text='이메일', max_length=100, null=True)),
                ('phone', models.CharField(blank=True, help_text='전화번호', max_length=15, null=True)),
                ('fax', models.CharField(blank=True, help_text='팩스번호', max_length=15, null=True)),
                ('business_type', models.CharField(blank=True, help_text='업태', max_length=100, null=True)),
                ('business_category', models.CharField(blank=True, help_text='종목', max_length=100, null=True)),
                ('address', models.TextField(blank=True, help_text='주소', null=True)),
                ('note', models.TextField(blank=True, help_text='비고', null=True)),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factory.factory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FactoryEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정일')),
                ('name', models.CharField(help_text='설비명', max_length=100)),
                ('status', models.CharField(choices=[('가동 대기', 'standby'), ('가동 중', 'running')], default='가동 대기', max_length=10)),
                ('priority', models.IntegerField(help_text='우선순위')),
                ('location', models.CharField(blank=True, help_text='위치', max_length=100, null=True)),
                ('note', models.TextField(blank=True, help_text='특이사항', null=True)),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factory.factory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FactoryMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정일')),
                ('email', models.EmailField(help_text='멤버/초대 이메일 주소', max_length=100)),
                ('role', models.CharField(choices=[('시스템 관리자', 'admin'), ('운영자', 'manager'), ('조회자', 'viewer')], default='조회자', help_text='멤버 권한', max_length=10)),
                ('status', models.CharField(choices=[('초대됨', 'invited'), ('활성', 'active')], default='초대됨', help_text='멤버 상태', max_length=10)),
                ('invitation_token', models.CharField(blank=True, help_text='초대 토큰 (초대 상태일 때만)', max_length=100, null=True, unique=True)),
                ('invitation_message', models.TextField(blank=True, help_text='초대 메시지', null=True)),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='factory.factory')),
                ('invited_by', models.ForeignKey(help_text='초대한 사용자', on_delete=django.db.models.deletion.CASCADE, related_name='invited_factory_members', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, help_text='팩토리 멤버 유저 (가입된 경우)', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
