# Generated by Django 5.0.10 on 2025-07-15 06:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('factory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='factory',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='factoryclient',
            name='factory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='factory.factory'),
        ),
        migrations.AddField(
            model_name='factoryequipment',
            name='factory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to='factory.factory'),
        ),
        migrations.AddField(
            model_name='factorymember',
            name='factory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='factory.factory'),
        ),
        migrations.AddField(
            model_name='factorymember',
            name='invited_by',
            field=models.ForeignKey(help_text='초대한 사용자', on_delete=django.db.models.deletion.CASCADE, related_name='invited_factory_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='factorymember',
            name='user',
            field=models.ForeignKey(help_text='팩토리 멤버 유저 (가입된 경우)', on_delete=django.db.models.deletion.CASCADE, related_name='factory_members', to=settings.AUTH_USER_MODEL),
        ),
    ]
