# Generated by Django 5.0.10 on 2025-07-08 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factory',
            name='billing_key',
            field=models.CharField(blank=True, help_text='결제 키', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='factoryequipment',
            name='location',
            field=models.CharField(blank=True, help_text='설비 위치', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='factoryequipment',
            name='priority',
            field=models.IntegerField(help_text='자동 배정 순위'),
        ),
    ]
