# Generated by Django 5.0.10 on 2025-07-21 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factoryclient',
            name='type',
            field=models.CharField(choices=[('수주처', 'customer'), ('발주처', 'supplier')], default='수주처', help_text='타입', max_length=10),
        ),
    ]
