# Generated by Django 5.0.10 on 2025-07-09 08:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0003_factory_billing_key_alter_factoryequipment_location_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='factory',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='factoryclient',
            name='factory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='factory.factory'),
        ),
        migrations.AlterField(
            model_name='factoryequipment',
            name='factory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to='factory.factory'),
        ),
        migrations.AlterField(
            model_name='factorymember',
            name='user',
            field=models.ForeignKey(blank=True, help_text='팩토리 멤버 유저 (가입된 경우)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factory_members', to=settings.AUTH_USER_MODEL),
        ),
    ]
