# Generated by Django 5.0.10 on 2025-07-22 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0003_factoryclient_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factory',
            name='name',
            field=models.CharField(blank=True, help_text='팩토리 이름', max_length=100, null=True),
        ),
    ]
