# Generated by Django 5.0.10 on 2025-07-22 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0004_alter_factory_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='factorymember',
            name='invited_at',
            field=models.DateTimeField(blank=True, help_text='초대 일시', null=True),
        ),
    ]
