# Generated by Django 5.0.10 on 2025-07-11 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0004_alter_factory_owner_alter_factoryclient_factory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factoryclient',
            name='manager',
            field=models.CharField(blank=True, help_text='담당자', max_length=100, null=True),
        ),
    ]
