# Generated by Django 5.0.10 on 2025-07-15 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0005_factoryclient_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='factory',
            name='inviting',
            field=models.JSONField(blank=True, default=list, help_text='초대 중인 이메일 목록'),
        ),
    ]
