# Generated by Django 5.0.10 on 2025-08-13 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0005_factorymember_invited_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factoryclient',
            name='type',
            field=models.CharField(choices=[('customer', '수주처'), ('supplier', '발주처')], default='customer', help_text='타입', max_length=10),
        ),
        migrations.AlterField(
            model_name='factoryequipment',
            name='status',
            field=models.CharField(choices=[('standby', '가동 대기'), ('running', '가동 중')], default='standby', max_length=10),
        ),
        migrations.AlterField(
            model_name='factorymember',
            name='role',
            field=models.CharField(choices=[('admin', '시스템 관리자'), ('manager', '운영자'), ('viewer', '조회자')], default='viewer', help_text='멤버 권한', max_length=10),
        ),
        migrations.AlterField(
            model_name='factorymember',
            name='status',
            field=models.CharField(choices=[('invited', '초대됨'), ('active', '활성')], default='invited', help_text='멤버 상태', max_length=10),
        ),
    ]
