# Generated by Django 5.0.10 on 2025-08-13 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0006_alter_factoryclient_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='factorymember',
            name='invited_by',
            field=models.ForeignKey(blank=True, help_text='초대한 사용자', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_factory_members', to=settings.AUTH_USER_MODEL),
        ),
    ]
