# Generated by Django 5.0.10 on 2025-08-20 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0007_alter_factorymember_invited_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='factorymember',
            name='barobill_id',
            field=models.CharField(blank=True, help_text='바로빌 ID', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='factorymember',
            name='barobill_password',
            field=models.CharField(blank=True, help_text='바로빌 비밀번호', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='factorymember',
            name='is_barobill_user',
            field=models.BooleanField(default=False, help_text='바로빌 사용자 여부'),
        ),
    ]
