# Generated by Django 5.0.10 on 2025-09-18 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0008_factorymember_barobill_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factoryclient',
            name='type',
        ),
        migrations.AddField(
            model_name='factoryclient',
            name='is_customer',
            field=models.BooleanField(default=False, help_text='수주처 역할 여부'),
        ),
        migrations.AddField(
            model_name='factoryclient',
            name='is_supplier',
            field=models.BooleanField(default=False, help_text='발주처 역할 여부'),
        ),
    ]
