# Generated by Django 5.0.10 on 2025-09-30 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0009_remove_factoryclient_type_factoryclient_is_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factory',
            name='is_trial',
        ),
    ]
