# Generated by Django 5.0.10 on 2025-11-02 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0010_remove_factory_is_trial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factorymember',
            name='role',
            field=models.CharField(choices=[('admin', '시스템 관리자'), ('manager', '운영자'), ('viewer', '조회자'), ('prod_manager', '생산담당자')], default='viewer', help_text='멤버 권한', max_length=20),
        ),
    ]
