# Generated by Django 5.0.10 on 2025-12-18 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0012_alter_factory_created_at_alter_factory_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factoryclient',
            name='account_holder',
            field=models.CharField(blank=True, help_text='예금주', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='factoryclient',
            name='account_number',
            field=models.CharField(blank=True, help_text='계좌번호', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='factoryclient',
            name='bank_name',
            field=models.CharField(blank=True, help_text='은행명', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='factoryclient',
            name='depositor_name',
            field=models.CharField(blank=True, help_text='입금자명', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='factory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='생성일'),
        ),
        migrations.AlterField(
            model_name='factory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='수정일'),
        ),
        migrations.AlterField(
            model_name='factoryclient',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='생성일'),
        ),
        migrations.AlterField(
            model_name='factoryclient',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='수정일'),
        ),
        migrations.AlterField(
            model_name='factoryequipment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='생성일'),
        ),
        migrations.AlterField(
            model_name='factoryequipment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='수정일'),
        ),
        migrations.AlterField(
            model_name='factorymember',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='생성일'),
        ),
        migrations.AlterField(
            model_name='factorymember',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='수정일'),
        ),
    ]
