# Generated by Django 5.0.10 on 2026-01-21 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0013_factoryclient_account_holder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factorymember',
            name='dashboard_layout',
            field=models.JSONField(blank=True, default=None, help_text='대시보드 위젯 레이아웃 설정', null=True),
        ),
    ]
