# Generated by Django 5.0.10 on 2025-07-11 09:01

import django.db.models.deletion
import django.utils.timezone
import user.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정일')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(help_text='이메일', max_length=100)),
                ('code', models.CharField(help_text='인증 코드', max_length=6)),
                ('is_verified', models.BooleanField(default=False, help_text='인증 여부')),
                ('verification_type', models.CharField(choices=[('signup', '회원가입'), ('password_reset', '비밀번호 재설정')], default='signup', help_text='인증 타입', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('first_name', models.CharField(editable=False, max_length=150)),
                ('last_name', models.CharField(editable=False, max_length=150)),
                ('username', models.CharField(editable=False, max_length=150)),
                ('email', models.EmailField(help_text='이메일', max_length=50, unique=True)),
                ('status', models.CharField(choices=[('비활성유저', '비활성유저'), ('활성유저', '활성유저'), ('관리자', '관리자'), ('탈퇴유저', '탈퇴유저')], default='비활성유저', help_text='회원 유형', max_length=10)),
                ('phone_number', models.CharField(blank=True, help_text='전화번호', max_length=15, null=True)),
                ('profile_image', models.CharField(blank=True, help_text='프로필 이미지', max_length=255, null=True)),
                ('terms_of_service', models.BooleanField(default=False, help_text='서비스 이용 약관 동의 여부')),
                ('privacy_policy_agreement', models.BooleanField(default=False, help_text='개인정보 처리 방침 동의 여부')),
                ('marketing_agreement', models.BooleanField(default=False, help_text='마케팅 정보 수신 동의 여부')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='custom_user_set', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='custom_user_permissions_set', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', user.models.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Jwt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access', models.TextField(help_text='Access Token')),
                ('refresh', models.TextField(help_text='Refresh Token')),
                ('user', models.OneToOneField(help_text='회원', on_delete=django.db.models.deletion.CASCADE, related_name='login_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
