# Generated by Django 5.0.10 on 2025-07-24 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='barobill_user_id',
            field=models.CharField(blank=True, help_text='바로빌 사용자 ID', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, help_text='이름', max_length=150, null=True),
        ),
    ]
