# Generated by Django 5.0.10 on 2025-08-13 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_barobill_user_id_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('inactive', '비활성유저'), ('active', '활성유저'), ('admin', '관리자'), ('withdraw', '탈퇴유저')], default='inactive', help_text='회원 유형', max_length=10),
        ),
    ]
