# Generated by Django 5.0.10 on 2025-06-17 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_add_uuid_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jwt',
            name='uuid_id',
        ),
        migrations.RemoveField(
            model_name='jwt',
            name='uuid_user_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='uuid_id',
        ),
    ]
