# Generated by Django 5.0.10 on 2025-06-17 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_jwt_uuid_id_remove_jwt_uuid_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='verification_type',
            field=models.CharField(choices=[('signup', 'signup'), ('password_reset', 'password_reset')], help_text='인증 타입', max_length=20),
        ),
    ]
