# Generated by Django 5.0.10 on 2025-12-31 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_emailverification_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('ko', '한국어'), ('en', 'English')], default='ko', help_text='언어 설정', max_length=10),
        ),
    ]
