# Generated by Django 5.0.10 on 2025-07-02 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_profile_image'),
        ('user', '0005_alter_emailverification_verification_type'),
    ]

    operations = [
    ]
