# Generated by Django 5.0.10 on 2025-06-17 05:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='품목명', max_length=100)),
                ('code', models.CharField(help_text='품목코드', max_length=50, unique=True)),
                ('specification', models.CharField(help_text='규격', max_length=100)),
                ('unit', models.CharField(help_text='단위', max_length=20)),
                ('current_stock', models.PositiveIntegerField(default=0, help_text='현재 재고')),
                ('expiration_date', models.DateField(blank=True, help_text='유통기한', null=True)),
                ('received_date', models.DateField(help_text='입고일자')),
                ('warehouse_location', models.CharField(help_text='창고 위치', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ItemMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(help_text='이 품목을 만드는데 필요한 자재 수량')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.item')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.material')),
            ],
            options={
                'unique_together': {('item', 'material')},
            },
        ),
        migrations.AddField(
            model_name='item',
            name='materials',
            field=models.ManyToManyField(blank=True, help_text='이 품목(Item)을 만드는데 사용된 자재(Material)들', related_name='items', through='item.ItemMaterial', to='material.material'),
        ),
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('return_quantity', models.PositiveIntegerField(help_text='반품수량')),
                ('return_date', models.DateField(help_text='반품일자')),
                ('item', models.ForeignKey(help_text='반품된 품목', on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='item.item')),
            ],
            options={
                'verbose_name': '반품',
                'verbose_name_plural': '반품',
                'ordering': ['-return_date'],
            },
        ),
    ]
