# Generated by Django 5.0.10 on 2025-06-22 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('factory', '0001_initial'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정일')),
                ('is_transaction_publish', models.BooleanField(default=False, help_text='거래명세서 발행 여부')),
                ('tax_invoice_status', models.CharField(choices=[('미발행', 'pending'), ('발행 중', 'processing'), ('발행 완료', 'completed')], default='미발행', help_text='세금계산서 발행 상태', max_length=10)),
                ('transact_date', models.DateField(help_text='거래명세서 발행 일자')),
                ('tax_invoice_date', models.DateField(help_text='세금계산서 발행 일자')),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factory.factory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정일')),
                ('due_date', models.DateField(help_text='납기일자')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factory.factoryclient')),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factory.factory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuotationProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정일')),
                ('quantity', models.IntegerField(help_text='수량')),
                ('unit_price', models.IntegerField(help_text='단가')),
                ('is_delivery', models.BooleanField(default=False, help_text='납품 여부')),
                ('delivery_date', models.DateField(blank=True, help_text='납품 일자', null=True)),
                ('product', models.ForeignKey(help_text='제품', on_delete=django.db.models.deletion.CASCADE, to='stock.product')),
                ('quotation', models.ForeignKey(help_text='견적서', on_delete=django.db.models.deletion.CASCADE, to='document.quotation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='quotation',
            name='products',
            field=models.ManyToManyField(help_text='견적서에 포함된 제품들', through='document.QuotationProduct', to='stock.product'),
        ),
    ]
