# Generated by Django 5.0.10 on 2025-07-03 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('document', '0001_initial'),
        ('factory', '0001_initial'),
        ('project', '0001_initial'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factory.factoryclient'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='factory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factory.factory'),
        ),
        migrations.AddField(
            model_name='quotationproduct',
            name='product',
            field=models.ForeignKey(help_text='제품', on_delete=django.db.models.deletion.CASCADE, to='stock.product'),
        ),
        migrations.AddField(
            model_name='quotationproduct',
            name='quotation',
            field=models.ForeignKey(help_text='견적서', on_delete=django.db.models.deletion.CASCADE, to='document.quotation'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='products',
            field=models.ManyToManyField(help_text='견적서에 포함된 제품들', through='document.QuotationProduct', to='stock.product'),
        ),
        migrations.AddField(
            model_name='taxinvoice',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factory.factoryclient'),
        ),
        migrations.AddField(
            model_name='taxinvoice',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project'),
        ),
        migrations.AddField(
            model_name='workinstruction',
            name='plans',
            field=models.ManyToManyField(blank=True, help_text='연결된 생산 계획들', null=True, to='project.projectplan'),
        ),
    ]
