# Generated by Django 5.0.10 on 2025-07-15 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('document', '0001_initial'),
        ('factory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='client',
            field=models.ForeignKey(blank=True, help_text='고객', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='factory.factoryclient'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='factory',
            field=models.ForeignKey(blank=True, help_text='공장', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='factory.factory'),
        ),
    ]
