# Generated by Django 5.0.10 on 2025-07-07 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('document', '0001_initial'),
        ('factory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factory.factoryclient'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='factory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factory.factory'),
        ),
    ]
