# Generated by Django 5.0.10 on 2025-07-08 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_initial'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workinstruction',
            name='plans',
            field=models.ManyToManyField(blank=True, help_text='연결된 생산 계획들', to='project.projectplan'),
        ),
        migrations.DeleteModel(
            name='TaxInvoice',
        ),
    ]
