# Generated by Django 5.0.10 on 2025-07-15 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('document', '0002_initial'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='project',
            field=models.ForeignKey(help_text='프로젝트', on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='project.project'),
        ),
    ]
