# Generated by Django 5.0.10 on 2025-07-09 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0003_alter_workinstruction_plans_delete_taxinvoice'),
        ('factory', '0004_alter_factory_owner_alter_factoryclient_factory_and_more'),
        ('project', '0003_project_tax_invoice_refund_product_and_more'),
        ('stock', '0003_materialhistory_cash_receipt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='products',
        ),
        migrations.AddField(
            model_name='quotation',
            name='project',
            field=models.ForeignKey(default=1, help_text='프로젝트', on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='project.project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quotation',
            name='uploaded_file',
            field=models.CharField(blank=True, help_text='업로드 파일', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='client',
            field=models.ForeignKey(help_text='고객', on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='factory.factoryclient'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='factory',
            field=models.ForeignKey(help_text='공장', on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='factory.factory'),
        ),
        migrations.AlterField(
            model_name='quotationproduct',
            name='product',
            field=models.ForeignKey(help_text='제품', on_delete=django.db.models.deletion.CASCADE, related_name='quotation_products', to='stock.product'),
        ),
        migrations.AlterField(
            model_name='quotationproduct',
            name='quotation',
            field=models.ForeignKey(help_text='견적서', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='document.quotation'),
        ),
        migrations.AlterField(
            model_name='workinstruction',
            name='plans',
            field=models.ManyToManyField(blank=True, help_text='연결된 생산 계획들', related_name='work_instructions', to='project.projectplan'),
        ),
    ]
