# Generated by Django 5.0.10 on 2025-07-15 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('document', '0003_initial'),
        ('project', '0001_initial'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationproduct',
            name='product',
            field=models.ForeignKey(help_text='제품', on_delete=django.db.models.deletion.CASCADE, related_name='quotation_products', to='stock.product'),
        ),
        migrations.AddField(
            model_name='quotationproduct',
            name='quotation',
            field=models.ForeignKey(help_text='견적서', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='document.quotation'),
        ),
        migrations.AddField(
            model_name='workinstruction',
            name='plans',
            field=models.ManyToManyField(blank=True, help_text='연결된 생산 계획들', related_name='work_instructions', to='project.projectplan'),
        ),
    ]
