# Generated by Django 5.0.10 on 2025-08-08 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationproduct',
            name='is_refund',
            field=models.BooleanField(default=False, help_text='반품 여부'),
        ),
    ]
