# Generated by Django 5.0.10 on 2025-07-11 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0004_remove_quotation_products_quotation_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='due_date',
            field=models.DateField(blank=True, help_text='납기일자', null=True),
        ),
    ]
