# Generated by Django 5.0.10 on 2025-08-08 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0005_quotationproduct_is_refund'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotationproduct',
            name='is_refund',
        ),
    ]
