# Generated by Django 5.0.10 on 2025-07-11 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0005_alter_quotation_due_date'),
        ('factory', '0005_factoryclient_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='client',
            field=models.ForeignKey(blank=True, help_text='고객', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='factory.factoryclient'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='factory',
            field=models.ForeignKey(blank=True, help_text='공장', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='factory.factory'),
        ),
    ]
