# Generated by Django 5.0.10 on 2025-08-14 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0006_remove_quotationproduct_is_refund'),
        ('factory', '0007_alter_factorymember_invited_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='client_info',
            field=models.JSONField(blank=True, default=dict, help_text='거래처 정보', null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='factory_info',
            field=models.JSONField(blank=True, default=dict, help_text='공장 정보', null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='type',
            field=models.CharField(choices=[('quotation', '견적서'), ('order', '주문서')], default='quotation', help_text='견적서 유형', max_length=10),
        ),
        migrations.AddField(
            model_name='quotationproduct',
            name='product_info',
            field=models.JSONField(blank=True, default=dict, help_text='제품 정보', null=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='client',
            field=models.ForeignKey(blank=True, help_text='거래처', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='factory.factoryclient'),
        ),
    ]
