# Generated by Django 5.0.10 on 2025-08-18 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0007_quotation_client_info_quotation_factory_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='due_date_notification',
            field=models.BooleanField(default=False, help_text='마감일 알림 여부'),
        ),
    ]
