# Generated by Django 5.0.10 on 2025-08-23 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0008_quotation_due_date_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='products_info',
            field=models.JSONField(blank=True, default=list, help_text='주문 확정 시 제품들 정보 (반품 항목은 추가되지 않도록)', null=True),
        ),
    ]
