# Generated by Django 5.0.10 on 2025-09-09 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0009_quotation_products_info'),
        ('factory', '0008_factorymember_barobill_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workinstruction',
            name='factory',
            field=models.ForeignKey(blank=True, help_text='공장', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_instructions', to='factory.factory'),
        ),
    ]
