# Generated by Django 5.0.10 on 2025-11-11 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0010_workinstruction_factory'),
        ('project', '0017_projectplan_material_consumed'),
    ]

    operations = [
        migrations.AddField(
            model_name='workinstruction',
            name='plan_info',
            field=models.JSONField(blank=True, default=list, help_text='과거 생산 계획 스냅샷 (불변, 아카이브된 데이터)', null=True),
        ),
        migrations.AlterField(
            model_name='workinstruction',
            name='plans',
            field=models.ManyToManyField(blank=True, help_text='연결된 생산 계획들 (오늘 것만, 실시간 변경 가능)', related_name='work_instructions', to='project.projectplan'),
        ),
    ]
