# Generated by Django 5.0.10 on 2025-11-14 05:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0011_add_plan_info_to_workinstruction'),
        ('project', '0017_projectplan_material_consumed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkInstructionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정일')),
                ('action', models.CharField(choices=[('added', '추가'), ('updated', '수정'), ('removed', '삭제'), ('memo_updated', '메모 수정')], help_text='변경 유형 (추가/수정/삭제/메모 수정)', max_length=20)),
                ('before_data', models.JSONField(blank=True, default=dict, help_text='변경 전 데이터', null=True)),
                ('after_data', models.JSONField(blank=True, default=dict, help_text='변경 후 데이터', null=True)),
                ('changed_by', models.ForeignKey(blank=True, help_text='변경한 사용자', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_instruction_histories', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(blank=True, help_text='생산 계획 (삭제된 경우 null)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_instruction_histories', to='project.projectplan')),
                ('work_instruction', models.ForeignKey(help_text='생산지시서', on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='document.workinstruction')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
