# Generated by Django 5.0.10 on 2025-11-11 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('factory', '0011_alter_factorymember_role'),
        ('stock', '0010_alter_materialhistory_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Substitute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정일')),
                ('name', models.CharField(blank=True, help_text="그룹명 (예: 'M8 볼트 그룹', 'SUS304 1.5t 판재 그룹')", max_length=100, null=True)),
                ('description', models.TextField(blank=True, help_text='그룹 설명', null=True)),
                ('factory', models.ForeignKey(help_text='공장', on_delete=django.db.models.deletion.CASCADE, related_name='substitutes', to='factory.factory')),
                ('materials', models.ManyToManyField(help_text='대체 가능한 자재 목록', related_name='substitutes', to='stock.material')),
            ],
            options={
                'verbose_name': '대체 자재 그룹',
                'verbose_name_plural': '대체 자재 그룹',
                'ordering': ['-created_at'],
            },
        ),
    ]
