# Generated by Django 5.0.10 on 2025-11-12 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0011_alter_factorymember_role'),
        ('stock', '0010_alter_materialhistory_client'),
        ('substitute', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='substitute',
            options={'ordering': ['-created_at'], 'verbose_name': '대체 자재 관계', 'verbose_name_plural': '대체 자재 관계'},
        ),
        migrations.AddField(
            model_name='substitute',
            name='source_material',
            field=models.ForeignKey(blank=True, help_text='원본 자재 (이 자재의 대체 가능한 자재들을 정의)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='substitute_relations', to='stock.material'),
        ),
        migrations.AddField(
            model_name='substitute',
            name='target_materials',
            field=models.ManyToManyField(help_text='대체 가능한 자재 목록 (단방향: source_material의 대체 자재들)', related_name='substituted_by_relations', to='stock.material'),
        ),
        migrations.RemoveField(
            model_name='substitute',
            name='materials',
        ),
        migrations.AlterUniqueTogether(
            name='substitute',
            unique_together={('factory', 'source_material')},
        ),
    ]
