# Generated by Django 5.0.10 on 2025-11-12 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('substitute', '0002_change_to_unidirectional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='substitute',
            name='description',
        ),
        migrations.RemoveField(
            model_name='substitute',
            name='name',
        ),
    ]
