# Generated by Django 5.0.10 on 2025-11-18 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0010_alter_materialhistory_client'),
        ('substitute', '0003_remove_name_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='substitute',
            options={'ordering': ['-created_at'], 'verbose_name': 'Substitute', 'verbose_name_plural': 'Substitutes'},
        ),
        migrations.AlterField(
            model_name='substitute',
            name='source_material',
            field=models.ForeignKey(help_text='이 자재의 대체 가능한 자재들을 정의', on_delete=django.db.models.deletion.CASCADE, related_name='substitute_relations', to='stock.material'),
        ),
    ]
