# Generated by Django 5.0.10 on 2025-12-12 21:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('substitute', '0004_alter_substitute_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='substitute',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='생성일'),
        ),
        migrations.AlterField(
            model_name='substitute',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='수정일'),
        ),
    ]
