# Generated by Django 5.0.10 on 2025-12-18 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('substitute', '0005_alter_substitute_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='substitute',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='생성일'),
        ),
        migrations.AlterField(
            model_name='substitute',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='수정일'),
        ),
    ]
