# Generated by Django 5.0.10 on 2025-06-17 05:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(help_text='회사명', max_length=100)),
                ('business_registration_number', models.CharField(help_text='사업자등록번호', max_length=20)),
                ('ceo_name', models.CharField(help_text='대표자명', max_length=50)),
                ('business_type', models.CharField(blank=True, help_text='업태', max_length=50, null=True)),
                ('business_item', models.CharField(blank=True, help_text='종목', max_length=50, null=True)),
                ('company_address', models.CharField(help_text='사업장 주소', max_length=200)),
                ('manager_name', models.CharField(help_text='담당자명', max_length=50)),
                ('manager_email', models.EmailField(help_text='담당자 이메일', max_length=100)),
                ('manager_phone', models.CharField(help_text='담당자 연락처', max_length=30)),
                ('manager_fax', models.CharField(blank=True, help_text='담당자 팩스번호', max_length=30, null=True)),
                ('memo', models.TextField(blank=True, help_text='비고', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuotationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('due_date', models.DateField(help_text='납기일자')),
                ('created_at', models.DateField(auto_now_add=True, help_text='견적서 생성일자')),
                ('status', models.CharField(help_text='상태', max_length=30)),
                ('contact', models.ForeignKey(help_text='연락처 정보', on_delete=django.db.models.deletion.CASCADE, related_name='quotation_requests', to='quotationRequest.contact')),
            ],
        ),
        migrations.CreateModel(
            name='QuotationRequestItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_name', models.CharField(help_text='품목', max_length=100)),
                ('item_code', models.CharField(help_text='품목 코드', max_length=50)),
                ('specification', models.CharField(help_text='규격', max_length=100)),
                ('unit', models.CharField(help_text='단위', max_length=20)),
                ('unit_price', models.PositiveIntegerField(help_text='단가')),
                ('quantity', models.PositiveIntegerField(help_text='제작수량')),
                ('amount', models.PositiveIntegerField(help_text='금액')),
                ('quotation_request', models.ForeignKey(help_text='견적 요청서', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quotationRequest.quotationrequest')),
            ],
        ),
    ]
