# Generated by Django 5.0.10 on 2025-07-15 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('factory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정일')),
                ('type', models.CharField(choices=[('경고', 'warning'), ('정보', 'information'), ('완료', 'completed')], default='경고', help_text='알림 유형', max_length=20)),
                ('case', models.CharField(choices=[('자재 부족', 'material_lack'), ('프로젝트 생산 계획 이상', 'project_warning'), ('제품 생산 완료', 'product_completed'), ('매출 세금계산서 발행 완료', 'sales_tax_invoice_published'), ('매입 세금계산서 발행 완료', 'purchase_tax_invoice_published'), ('영수증 발행 완료', 'cash_receipt_published'), ('권한 변경', 'permission_changed'), ('납기일 임박', 'due_date_approaching'), ('생산 일정 변경', 'production_schedule_changed')], default='자재 부족', help_text='알림 사유', max_length=20)),
                ('content', models.TextField(help_text='알림 내용')),
                ('is_read', models.BooleanField(default=False, help_text='읽음 여부')),
                ('receiver', models.ForeignKey(help_text='수신자', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='factory.factorymember')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
