# Generated by Django 5.0.10 on 2025-07-07 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('factory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정일')),
                ('type', models.CharField(choices=[('납기일 임박', 'due_date'), ('생산 완료', 'manufactured'), ('부족', 'lack'), ('세금계산서 미발행', 'tax_un_published')], default='납기일 임박', help_text='알림 유형', max_length=20)),
                ('content', models.TextField(help_text='알림 내용')),
                ('is_read', models.BooleanField(default=False, help_text='읽음 여부')),
                ('receiver', models.ForeignKey(help_text='수신자', on_delete=django.db.models.deletion.CASCADE, to='factory.factorymember')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
