# Generated by Django 5.0.10 on 2025-07-08 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='case',
            field=models.CharField(choices=[('자재 부족', 'material_lack'), ('프로젝트 생산 계획 이상', 'project_warning'), ('제품 생산 완료', 'product_completed'), ('매출 세금계산서 발행 완료', 'sales_tax_invoice_published'), ('매입 세금계산서 발행 완료', 'purchase_tax_invoice_published'), ('영수증 발행 완료', 'cash_receipt_published'), ('권한 변경', 'permission_changed'), ('납기일 임박', 'due_date_approaching'), ('생산 일정 변경', 'production_schedule_changed')], default='자재 부족', help_text='알림 사유', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('경고', 'warning'), ('정보', 'information'), ('완료', 'completed')], default='경고', help_text='알림 유형', max_length=20),
        ),
    ]
