# Generated by Django 5.0.10 on 2025-08-10 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='case',
            field=models.CharField(choices=[('material_lack', '자재 부족'), ('project_warning', '프로젝트 생산 계획 이상'), ('product_completed', '제품 생산 완료'), ('sales_tax_invoice_published', '매출 세금계산서 발행 완료'), ('purchase_tax_invoice_published', '매입 세금계산서 발행 완료'), ('cash_receipt_published', '영수증 발행 완료'), ('permission_changed', '권한 변경'), ('due_date_approaching', '납기일 임박'), ('production_schedule_changed', '생산 일정 변경')], default='material_lack', help_text='알림 사유', max_length=30),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('warning', '경고'), ('information', '정보'), ('completed', '완료')], default='warning', help_text='알림 유형', max_length=20),
        ),
    ]
