# Generated by Django 5.0.10 on 2025-07-09 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0004_alter_factory_owner_alter_factoryclient_factory_and_more'),
        ('notification', '0002_notification_case_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='receiver',
            field=models.ForeignKey(help_text='수신자', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='factory.factorymember'),
        ),
    ]
