# Generated by Django 5.0.10 on 2025-07-09 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0004_alter_factory_owner_alter_factoryclient_factory_and_more'),
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='tax_invoice_count',
            field=models.IntegerField(default=1, help_text='세금계산서 발행 제한 개수'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscriptionhistory',
            name='factory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_histories', to='factory.factory'),
        ),
        migrations.AlterField(
            model_name='subscriptionhistory',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_histories', to='subscription.subscription'),
        ),
    ]
