# Generated by Django 5.0.10 on 2025-08-07 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='type',
            field=models.CharField(choices=[('trial', '트라이얼'), ('basic', '기본'), ('partners', '파트너')], default='trial', max_length=10),
        ),
    ]
