# Generated by Django 5.0.10 on 2025-08-10 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_alter_subscription_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionhistory',
            name='billing_key',
            field=models.CharField(blank=True, help_text='빌링키', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionhistory',
            name='customer_key',
            field=models.CharField(blank=True, help_text='고객키', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정일')),
                ('payment_key', models.CharField(blank=True, help_text='결제 키', max_length=255, null=True)),
                ('order_id', models.CharField(blank=True, help_text='주문 ID', max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='결제 금액', max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', '대기중'), ('DONE', '완료'), ('CANCELED', '취소'), ('FAILED', '실패')], default='PENDING', help_text='결제 상태', max_length=20)),
                ('method', models.CharField(blank=True, help_text='결제 방법', max_length=50, null=True)),
                ('approved_at', models.DateTimeField(blank=True, help_text='승인 일시', null=True)),
                ('failure_code', models.CharField(blank=True, help_text='실패 코드', max_length=50, null=True)),
                ('failure_message', models.CharField(blank=True, help_text='실패 메시지', max_length=255, null=True)),
                ('subscription_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='subscription.subscriptionhistory')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
