# Generated by Django 5.0.10 on 2025-09-13 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_subscriptionhistory_billing_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='card_company',
            field=models.CharField(blank=True, help_text='카드사명', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='card_number',
            field=models.CharField(blank=True, help_text='마스킹된 카드번호', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='card_owner_type',
            field=models.CharField(blank=True, help_text='카드 소유자 타입 (개인/법인)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='card_type',
            field=models.CharField(blank=True, help_text='카드 타입 (신용/체크)', max_length=20, null=True),
        ),
    ]
