# Generated by Django 5.0.10 on 2025-09-15 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_payment_card_company_payment_card_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionhistory',
            name='is_canceled',
            field=models.BooleanField(default=False, help_text='구독 취소 여부 (True면 자동 갱신하지 않음)'),
        ),
    ]
