# Generated by Django 5.0.10 on 2025-09-16 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0005_subscriptionhistory_is_canceled'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionhistory',
            name='auth_key',
            field=models.CharField(blank=True, help_text='인증키', max_length=255, null=True),
        ),
    ]
