# Generated by Django 5.0.10 on 2025-09-16 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0008_factorymember_barobill_id_and_more'),
        ('subscription', '0006_subscriptionhistory_auth_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정일')),
                ('auth_key', models.CharField(help_text='인증키', max_length=255)),
                ('customer_key', models.CharField(help_text='고객키', max_length=255)),
                ('billing_key', models.CharField(help_text='빌링키', max_length=255)),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_auths', to='factory.factory')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
