# Generated by Django 5.0.10 on 2025-09-24 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0007_paymentauth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentauth',
            name='auth_key',
        ),
        migrations.AddField(
            model_name='paymentauth',
            name='card_company',
            field=models.CharField(default='', help_text='카드사명', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentauth',
            name='card_number',
            field=models.CharField(default='', help_text='마스킹된 카드번호', max_length=50),
            preserve_default=False,
        ),
    ]
