# Generated by Django 5.0.10 on 2025-12-12 21:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0008_remove_paymentauth_auth_key_paymentauth_card_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='생성일'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='수정일'),
        ),
        migrations.AlterField(
            model_name='paymentauth',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='생성일'),
        ),
        migrations.AlterField(
            model_name='paymentauth',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='수정일'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='생성일'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='수정일'),
        ),
        migrations.AlterField(
            model_name='subscriptionhistory',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='생성일'),
        ),
        migrations.AlterField(
            model_name='subscriptionhistory',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='수정일'),
        ),
    ]
