# Generated by Django 5.0.10 on 2025-12-18 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0009_alter_payment_created_at_alter_payment_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='생성일'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='수정일'),
        ),
        migrations.AlterField(
            model_name='paymentauth',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='생성일'),
        ),
        migrations.AlterField(
            model_name='paymentauth',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='수정일'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='생성일'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='수정일'),
        ),
        migrations.AlterField(
            model_name='subscriptionhistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='생성일'),
        ),
        migrations.AlterField(
            model_name='subscriptionhistory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='수정일'),
        ),
    ]
