"""
Django settings for cfehome project.

Generated by 'django-admin startproject' using Django 5.0.10.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from decouple import config
from pathlib import Path
from zeep import Client
import sys
import os

# 시간대 환경 변수 설정 (Django 설정 로드 전에 설정)
os.environ.setdefault("TZ", "Asia/Seoul")

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("DJANGO_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DJANGO_DEBUG", default=False, cast=bool)

ALLOWED_HOSTS = [
    ".railway.app",
    "api.factoryx.work",
]

ASGI_APPLICATION = "cfehome.asgi.application"

if DEBUG:
    ALLOWED_HOSTS += [
        "127.0.0.1",
        "localhost",
        "0.0.0.0",
    ]

CSRF_TRUSTED_ORIGINS = [
    "http://*.railway.app",
    "https://*.railway.app",
    "http://api.factoryx.work",
    "https://api.factoryx.work",
]


# Application definition

INSTALLED_APPS = [
    # django channels
    "channels",
    "daphne",
    # django default apps
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # third party
    "corsheaders",
    "django_crontab",
    # local apps
    "aws",
    "user",
    "commando",
    "common",
    "factory",
    "document",
    "project",
    "subscription",
    "notification",
    "stock",
    "repackaging",
    "tax",
    "location",
    "barobill",
    "scheduling",
    # v2
    "unit_conversion",
    "substitute",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "cfehome.urls"

CORS_URLS_REGEX = r"^/v(1|2)/.*$"

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOWED_ORIGINS = []
ENV_CORS_ALLOWED_ORIGINS = config("CORS_ALLOWED_ORIGINS", cast=str, default="")
for origin in ENV_CORS_ALLOWED_ORIGINS.split(","):
    if origin.strip():  # 빈 문자열 체크
        CORS_ALLOWED_ORIGINS.append(origin.strip().lower())

# cors & csrf
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SAMESITE = "None"
CSRF_COOKIE_SAMESITE = "None"

# DJANGO ENVIRONMENT
DJANGO_ENV_NAME = config("DJANGO_ENV_NAME", default=None)

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "cfehome.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

CONN_MAX_AGE = config("CONN_MAX_AGE", cast=int, default=300)
DATABASE_URL = config("DATABASE_URL", default=None)
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    },
}

if DATABASE_URL is not None:
    import dj_database_url

    DATABASES = {
        "default": dj_database_url.config(
            default=DATABASE_URL,
            conn_max_age=CONN_MAX_AGE,
            conn_health_checks=True,
        ),
    }

    # PostgreSQL 시간대 설정 (Neon 호환)
    if "postgresql" in DATABASE_URL or "postgres" in DATABASE_URL:
        DATABASES["default"]["OPTIONS"] = {"options": "-c timezone=Asia/Seoul"}

if "test" in sys.argv:
    DATABASES["default"] = {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "ko-kr"

TIME_ZONE = "Asia/Seoul" #  # USE_TZ=False일 때는 거의 사용 안 됨 (하지만 명시적으로 남겨두는 것도 좋음)

USE_I18N = True

USE_TZ = False # Django가 시스템 시간대를 사용

AUTH_USER_MODEL = "user.User"


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "static/"
STATICFILES_BASE_DIR = BASE_DIR / "staticfiles"
STATICFILES_BASE_DIR.mkdir(exist_ok=True, parents=True)
STATICFILES_VENDOR_DIR = STATICFILES_BASE_DIR / "vendors"

STATICFILES_DIRS = [STATICFILES_BASE_DIR]

STATIC_ROOT = BASE_DIR / "local-cdn"

STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ninja settings
NINJA_PAGINATION_CLASS = "api.pagination.CustomPageNumberPagination"
PAGINATION_PER_PAGE = 10

# login jwt token expiration
ACCESS_TOKEN_EXPIRATION_TIME = 365 * 60 * 60 * 24  # 1 years
REFRESH_TOKEN_EXPIRATION_TIME = 2 * 365 * 60 * 60 * 24  # 100 years

if DEBUG:
    FRONTEND_URL = "http://127.0.0.1:3000"
else:
    FRONTEND_URL = config("FRONTEND_URL", default=None)

# Redis Cache Settings
REDIS_HOST = config("REDIS_HOST", default="redis")  # Redis 호스트
REDIS_PORT = int(config("REDIS_PORT", default=6379))  # Redis
REDIS_DB = int(config("REDIS_DB", default=1))  # Redis 데이터베이스 인덱스
REDIS_CACHE_DB = int(
    config("REDIS_CACHE_DB", default=0)
)  # 캐시용 Redis 데이터베이스 인덱스
REDIS_PASSWORD = config("REDIS_PASSWORD", default=None)
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": f"redis://:{REDIS_PASSWORD}@{REDIS_HOST}:{REDIS_PORT}/{REDIS_DB}",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "IGNORE_EXCEPTIONS": True,  # 캐시 오류 시 애플리케이션 계속 실행
            "SOCKET_CONNECT_TIMEOUT": 5,  # 연결 타임아웃(초)
            "SOCKET_TIMEOUT": 5,  # 통신 타임아웃(초)
            "CONNECTION_POOL_KWARGS": {"max_connections": 50},  # 최대 연결 수
        },
        "KEY_PREFIX": "django",  # 키 충돌 방지를 위한 접두사
        "TIMEOUT": 300,  # 기본 캐시 만료 시간(초)
    }
}
if REDIS_PASSWORD:
    CHANNEL_REDIS_URL = (
        f"redis://:{REDIS_PASSWORD}@{REDIS_HOST}:{REDIS_PORT}/{REDIS_DB}"
    )
else:
    CHANNEL_REDIS_URL = f"redis://{REDIS_HOST}:{REDIS_PORT}/{REDIS_DB}"

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [CHANNEL_REDIS_URL],
            "symmetric_encryption_keys": [SECRET_KEY],  # 보안 강화
            "capacity": 1500,  # 채널 용량
            "expiry": 60,  # 메시지 만료 시간 (초)
        },
        "OPTIONS": {
            "connection_timeout": 5,  # 연결 타임아웃
            "socket_timeout": 5,  # 소켓 타임아웃
            "max_connections": 50,  # 최대 연결 수
        },
    },
}

# AWS SES Email Settings
USE_SES = config("USE_SES", default=False, cast=bool)

if USE_SES:
    # AWS SES Configuration
    AWS_ACCESS_KEY_ID = config("AWS_ACCESS_KEY_ID", default=None)
    AWS_SECRET_ACCESS_KEY = config("AWS_SECRET_ACCESS_KEY", default=None)
    AWS_DEFAULT_REGION = config("AWS_DEFAULT_REGION", default="ap-northeast-2")
    AWS_SES_REGION = config("AWS_SES_REGION", default="ap-northeast-2")

    # Email backend using SES
    EMAIL_BACKEND = "user.backends.SESEmailBackend"

    # Default from email
    DEFAULT_FROM_EMAIL = config("DEFAULT_FROM_EMAIL", default="noreply@yourdomain.com")
    SERVER_EMAIL = DEFAULT_FROM_EMAIL
else:
    # Console backend for development
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
    DEFAULT_FROM_EMAIL = "noreply@localhost"

# AWS S3 Storage Settings
AWS_ACCESS_KEY_ID = config("AWS_ACCESS_KEY_ID", default=None)
AWS_SECRET_ACCESS_KEY = config("AWS_SECRET_ACCESS_KEY", default=None)
AWS_REGION = config("AWS_REGION", default="ap-northeast-2")
AWS_CLOUDFRONT_URL = config("AWS_CLOUDFRONT_URL", default=None)
AWS_STORAGE_BUCKET_NAME = config("AWS_STORAGE_BUCKET_NAME", default=None)

# Barobill settings
BAROBILL_CERT_KEY = config("BAROBILL_CERT_KEY", default=None)
ENABLE_BAROBILL = config("ENABLE_BAROBILL", default=False, cast=bool)
if ENABLE_BAROBILL:
    BAROBILL_CLIENT = Client(
        "https://testws.baroservice.com/TI.asmx?WSDL"
    )  # 테스트서버
    # BAROBILL_CLIENT = Client("https://ws.baroservice.com/TI.asmx?WSDL")  # 운영서버
    BAROBILL_CASHBILL_CLIENT = Client(
        "https://testws.baroservice.com/CASHBILL.asmx?WSDL"
    )  # 테스트서버
    # BAROBILL_CASHBILL_CLIENT = Client("https://ws.baroservice.com/CASHBILL.asmx?WSDL")  # 운영서버
else:
    BAROBILL_CLIENT = None
    BAROBILL_CASHBILL_CLIENT = None

# Django Crontab Settings
# ⚠️ 주의: django-crontab은 로컬 개발 환경에서만 작동합니다.
# Railway 등 PaaS 환경에서는 cron을 직접 실행할 수 없으므로 이 설정은 무시됩니다.
# 
# 프로덕션 스케줄링:
# - QStash 등 외부 스케줄러를 통해 /v1/scheduling/* API를 호출하는 방식으로 처리됩니다.
# - 모든 스케줄링 작업은 scheduling API로 마이그레이션되었습니다.
# 
# 로컬에서 테스트하려면:
#   python manage.py crontab add
#   python manage.py crontab show
#
# 프로덕션에서는 QStash에서 다음 API들을 호출하도록 설정하세요:
# 
# 구독 자동 갱신 (2개의 스케줄 필요):
# 1. 매일 오전 6시: POST /v1/scheduling/subscription/renew?days=1
# 2. 매일 오전 6시 30분: POST /v1/scheduling/subscription/renew?days=0
# 
# 기타 스케줄링:
# - 매일 오전 12시(자정): POST /v1/scheduling/account/overdue
# - 매분 실행: POST /v1/scheduling/project-plan/start
# - 매분 실행: POST /v1/scheduling/project-plan/end
# - 매일 자정: POST /v1/scheduling/work-instruction
# - 한국시간 기준 오후 2시마다: POST /v1/scheduling/project/deadline
# - 세금계산서 상태 조회: POST /v1/scheduling/tax/state
#
CRONJOBS = [
    # 모든 작업이 scheduling API로 마이그레이션되었으므로 주석 처리합니다.
    # 로컬 테스트가 필요한 경우 아래 주석을 해제하세요.
    #
    # # 매일 오전 6시에 구독 자동 갱신 실행 (1일 후 만료되는 구독)
    # (
    #     "0 6 * * *",
    #     "subscription.management.commands.renew_subscriptions.Command.handle",
    #     "--days=1",
    # ),
    # # 매일 오전 6시 30분에 구독 자동 갱신 실행 (당일 만료되는 구독 - 마지막 기회)
    # (
    #     "30 6 * * *",
    #     "subscription.management.commands.renew_subscriptions.Command.handle",
    #     "--days=0",
    # ),
    # # 매일 오전 12시(자정)에 약정지급일이 지난 채권/채무 상태를 연체로 업데이트
    # (
    #     "0 0 * * *",
    #     "tax.management.commands.update_overdue_accounts.Command.handle",
    # ),
]

# Toss Payments Settings
TOSS_PAYMENTS_SECRET_KEY = config("TOSS_PAYMENTS_SECRET_KEY", default=None)
TOSS_PAYMENTS_CLIENT_KEY = config("TOSS_PAYMENTS_CLIENT_KEY", default=None)
TOSS_PAYMENTS_BASE_URL = "https://api.tosspayments.com"

# Scheduling
SCHEDULING_SECRET_KEY = config("SCHEDULING_SECRET_KEY", default=None)

# send-email with attachment
DATA_UPLOAD_MAX_MEMORY_SIZE = 30 * 1024 * 1024  # 30MB

# Trial period months
TRIAL_PERIOD_MONTHS = 1
