"""
Django settings for cfehome project.

Generated by 'django-admin startproject' using Django 5.0.10.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from decouple import config
from pathlib import Path
from zeep import Client
import sys
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("DJANGO_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DJANGO_DEBUG", default=False, cast=bool)

ALLOWED_HOSTS = [
    ".railway.app",
]

ASGI_APPLICATION = "cfehome.asgi.application"

if DEBUG:
    ALLOWED_HOSTS += [
        "127.0.0.1",
        "localhost",
        "0.0.0.0",
    ]

CSRF_TRUSTED_ORIGINS = [
    "http://*.railway.app",
    "https://*.railway.app",
]


# Application definition

INSTALLED_APPS = [
    # django channels
    "channels",
    "daphne",
    # django default apps
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # third party
    "corsheaders",
    "django_crontab",
    # local apps
    "aws",
    "user",
    "commando",
    "common",
    "factory",
    "document",
    "project",
    "subscription",
    "notification",
    "stock",
    "tax",
    "location",
    "barobill",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "cfehome.urls"

CORS_URLS_REGEX = r"^/v1/.*$"

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOWED_ORIGINS = []
ENV_CORS_ALLOWED_ORIGINS = config("CORS_ALLOWED_ORIGINS", cast=str, default="")
for origin in ENV_CORS_ALLOWED_ORIGINS.split(","):
    if origin.strip():  # 빈 문자열 체크
        CORS_ALLOWED_ORIGINS.append(origin.strip().lower())

# cors & csrf
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SAMESITE = "None"
CSRF_COOKIE_SAMESITE = "None"

# DJANGO ENVIRONMENT
DJANGO_ENV_NAME = config("DJANGO_ENV_NAME", default=None)

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "cfehome.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

CONN_MAX_AGE = config("CONN_MAX_AGE", cast=int, default=300)
DATABASE_URL = config("DATABASE_URL", default=None)
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    },
}
if DATABASE_URL is not None:
    import dj_database_url

    DATABASES = {
        "default": dj_database_url.config(
            default=DATABASE_URL,
            conn_max_age=CONN_MAX_AGE,
            conn_health_checks=True,
        ),
    }

if "test" in sys.argv:
    DATABASES["default"] = {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "ko-kr"

TIME_ZONE = "Asia/Seoul"

USE_I18N = True

USE_TZ = True

AUTH_USER_MODEL = "user.User"


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "static/"
STATICFILES_BASE_DIR = BASE_DIR / "staticfiles"
STATICFILES_BASE_DIR.mkdir(exist_ok=True, parents=True)
STATICFILES_VENDOR_DIR = STATICFILES_BASE_DIR / "vendors"

STATICFILES_DIRS = [STATICFILES_BASE_DIR]

STATIC_ROOT = BASE_DIR / "local-cdn"

STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ninja settings
NINJA_PAGINATION_CLASS = "api.pagination.CustomPageNumberPagination"
PAGINATION_PER_PAGE = 10

# login jwt token expiration
ACCESS_TOKEN_EXPIRATION_TIME = 365 * 60 * 60 * 24  # 1 years
REFRESH_TOKEN_EXPIRATION_TIME = 2 * 365 * 60 * 60 * 24  # 100 years

if DEBUG:
    FRONTEND_URL = "http://127.0.0.1:3000"
else:
    FRONTEND_URL = config("FRONTEND_URL", default=None)

# Redis Cache Settings
REDIS_HOST = config("REDIS_HOST", default="redis")  # Redis 호스트
REDIS_PORT = int(config("REDIS_PORT", default=6379))  # Redis
REDIS_DB = int(config("REDIS_DB", default=1))  # Redis 데이터베이스 인덱스
REDIS_CACHE_DB = int(
    config("REDIS_CACHE_DB", default=0)
)  # 캐시용 Redis 데이터베이스 인덱스
REDIS_PASSWORD = config("REDIS_PASSWORD", default=None)
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": f"redis://:{REDIS_PASSWORD}@{REDIS_HOST}:{REDIS_PORT}/{REDIS_DB}",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "IGNORE_EXCEPTIONS": True,  # 캐시 오류 시 애플리케이션 계속 실행
            "SOCKET_CONNECT_TIMEOUT": 5,  # 연결 타임아웃(초)
            "SOCKET_TIMEOUT": 5,  # 통신 타임아웃(초)
            "CONNECTION_POOL_KWARGS": {"max_connections": 50},  # 최대 연결 수
        },
        "KEY_PREFIX": "django",  # 키 충돌 방지를 위한 접두사
        "TIMEOUT": 300,  # 기본 캐시 만료 시간(초)
    }
}
if REDIS_PASSWORD:
    CHANNEL_REDIS_URL = (
        f"redis://:{REDIS_PASSWORD}@{REDIS_HOST}:{REDIS_PORT}/{REDIS_DB}"
    )
else:
    CHANNEL_REDIS_URL = f"redis://{REDIS_HOST}:{REDIS_PORT}/{REDIS_DB}"

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [CHANNEL_REDIS_URL],
            "symmetric_encryption_keys": [SECRET_KEY],  # 보안 강화
            "capacity": 1500,  # 채널 용량
            "expiry": 60,  # 메시지 만료 시간 (초)
        },
        "OPTIONS": {
            "connection_timeout": 5,  # 연결 타임아웃
            "socket_timeout": 5,  # 소켓 타임아웃
            "max_connections": 50,  # 최대 연결 수
        },
    },
}

# AWS SES Email Settings
USE_SES = config("USE_SES", default=False, cast=bool)

if USE_SES:
    # AWS SES Configuration
    AWS_ACCESS_KEY_ID = config("AWS_ACCESS_KEY_ID", default=None)
    AWS_SECRET_ACCESS_KEY = config("AWS_SECRET_ACCESS_KEY", default=None)
    AWS_DEFAULT_REGION = config("AWS_DEFAULT_REGION", default="ap-northeast-2")
    AWS_SES_REGION = config("AWS_SES_REGION", default="ap-northeast-2")

    # Email backend using SES
    EMAIL_BACKEND = "user.backends.SESEmailBackend"

    # Default from email
    DEFAULT_FROM_EMAIL = config("DEFAULT_FROM_EMAIL", default="noreply@yourdomain.com")
    SERVER_EMAIL = DEFAULT_FROM_EMAIL
else:
    # Console backend for development
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
    DEFAULT_FROM_EMAIL = "noreply@localhost"

# AWS S3 Storage Settings
AWS_ACCESS_KEY_ID = config("AWS_ACCESS_KEY_ID", default=None)
AWS_SECRET_ACCESS_KEY = config("AWS_SECRET_ACCESS_KEY", default=None)
AWS_REGION = config("AWS_REGION", default="ap-northeast-2")
AWS_CLOUDFRONT_URL = config("AWS_CLOUDFRONT_URL", default=None)
AWS_STORAGE_BUCKET_NAME = config("AWS_STORAGE_BUCKET_NAME", default=None)

# Barobill settings
BAROBILL_CERT_KEY = config("BAROBILL_CERT_KEY", default=None)
BAROBILL_CLIENT = Client("https://testws.baroservice.com/TI.asmx?WSDL")  # 테스트서버
# BAROBILL_CLIENT = Client("https://ws.baroservice.com/TI.asmx?WSDL")  # 운영서버
BAROBILL_CASHBILL_CLIENT = Client(
    "https://testws.baroservice.com/CASHBILL.asmx?WSDL"
)  # 테스트서버
# BAROBILL_CASHBILL_CLIENT = Client("https://ws.baroservice.com/CASHBILL.asmx?WSDL")  # 운영서버

# Django Crontab Settings
CRONJOBS = [
    # 매일 오전 9시에 프로덕션 상태 업데이트 실행
    (
        "0 9 * * *",
        "project.management.commands.update_production_status.Command.handle",
    ),
]

# Toss Payments Settings
TOSS_PAYMENTS_SECRET_KEY = "test_sk_..."  # 실제 환경에서는 환경변수로 관리
TOSS_PAYMENTS_CLIENT_KEY = "test_ck_..."
TOSS_PAYMENTS_BASE_URL = "https://api.tosspayments.com"
