# Generated by Django 5.0.10 on 2025-06-15 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정일')),
                ('memo_type', models.CharField(choices=[('general', '일반'), ('important', '중요'), ('urgent', '긴급'), ('reminder', '알림'), ('note', '참고')], default='general', help_text='메모 타입', max_length=20)),
                ('title', models.CharField(help_text='제목', max_length=200)),
                ('content', models.TextField(help_text='내용')),
            ],
            options={
                'verbose_name': '메모',
                'verbose_name_plural': '메모',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='단위코드', max_length=20, unique=True)),
                ('name', models.CharField(help_text='단위명', max_length=50)),
                ('description', models.TextField(blank=True, help_text='설명')),
                ('is_active', models.BooleanField(default=True, help_text='사용여부')),
            ],
        ),
    ]
