# Generated by Django 5.0.10 on 2025-07-08 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Memo',
        ),
        migrations.DeleteModel(
            name='Unit',
        ),
    ]
