# Generated by Django 5.0.10 on 2025-07-07 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정일')),
                ('type', models.CharField(choices=[('material', 'material'), ('product', 'product')], default='material', max_length=10)),
                ('location', models.CharField(help_text='위치', max_length=100)),
                ('images', models.JSONField(blank=True, default=list, help_text='위치 이미지 URL 목록', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
