# Generated by Django 5.0.10 on 2025-08-13 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='type',
            field=models.CharField(choices=[('material', '자재'), ('product', '제품')], default='material', max_length=10),
        ),
    ]
