# Generated by Django 5.0.10 on 2025-11-02 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_alter_location_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='detail_location',
            field=models.CharField(blank=True, help_text='상세위치', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='email',
            field=models.ForeignKey(blank=True, help_text='이메일의 Id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='location',
            name='memo',
            field=models.TextField(blank=True, help_text='메모', null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', '시스템 관리자'), ('manager', '운영자'), ('viewer', '조회자'), ('prod_manager', '생산담당자')], help_text='역할', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='location',
            field=models.CharField(blank=True, help_text='창고위치명', max_length=100, null=True),
        ),
    ]
