# Generated by Django 5.0.10 on 2025-11-02 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0011_alter_factorymember_role'),
        ('location', '0003_location_detail_location_location_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='email',
        ),
        migrations.AddField(
            model_name='location',
            name='member',
            field=models.ForeignKey(blank=True, help_text='팩토리 member id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='factory.factorymember'),
        ),
    ]
