# Generated by Django 5.0.10 on 2025-11-05 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0004_remove_location_email_location_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='role',
        ),
    ]
