# Generated by Django 5.0.10 on 2025-11-21 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock', '0012_alter_product_buffer_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialRepackaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정일')),
                ('lot_number', models.CharField(help_text='소분된 LOT 번호 (부모 로트번호-01, -02 형식으로 자동 생성)', max_length=100)),
                ('quantity', models.IntegerField(help_text='현재 잔량')),
                ('warehouse_location', models.CharField(blank=True, help_text='창고 위치', max_length=100, null=True)),
                ('expiration_date', models.DateField(blank=True, help_text='유통기한', null=True)),
                ('parent_history', models.ForeignKey(help_text='부모 구매 이력', on_delete=django.db.models.deletion.CASCADE, related_name='repackagings', to='stock.materialhistory')),
            ],
            options={
                'verbose_name': '원자재 소분 내역',
                'verbose_name_plural': '원자재 소분 내역',
                'ordering': ['-created_at'],
            },
        ),
    ]
