# Generated by Django 5.0.10 on 2025-11-27 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repackaging', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialrepackaging',
            name='quantity',
            field=models.DecimalField(decimal_places=2, help_text='현재 잔량', max_digits=12),
        ),
    ]
